// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package zia

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Use the **zia_firewall_filtering_ip_source_groups** data source to get information about ip source groups available in the Zscaler Internet Access cloud firewall. This data source can then be associated with a ZIA firewall filtering rule.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi-zia/sdk/go/zia"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := zia.GetZIAFirewallFilteringSourceIPGroups(ctx, &zia.GetZIAFirewallFilteringSourceIPGroupsArgs{
//				Name: pulumi.StringRef("example"),
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func GetZIAFirewallFilteringSourceIPGroups(ctx *pulumi.Context, args *GetZIAFirewallFilteringSourceIPGroupsArgs, opts ...pulumi.InvokeOption) (*GetZIAFirewallFilteringSourceIPGroupsResult, error) {
	opts = pkgInvokeDefaultOpts(opts)
	var rv GetZIAFirewallFilteringSourceIPGroupsResult
	err := ctx.Invoke("zia:index/getZIAFirewallFilteringSourceIPGroups:getZIAFirewallFilteringSourceIPGroups", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getZIAFirewallFilteringSourceIPGroups.
type GetZIAFirewallFilteringSourceIPGroupsArgs struct {
	// The ID of the ip source group resource.
	Id *int `pulumi:"id"`
	// The name of the ip source group to be exported.
	Name *string `pulumi:"name"`
}

// A collection of values returned by getZIAFirewallFilteringSourceIPGroups.
type GetZIAFirewallFilteringSourceIPGroupsResult struct {
	// (String)
	Description string `pulumi:"description"`
	// The ID of this resource.
	Id int `pulumi:"id"`
	// (List of String)
	IpAddresses []string `pulumi:"ipAddresses"`
	Name        string   `pulumi:"name"`
}

func GetZIAFirewallFilteringSourceIPGroupsOutput(ctx *pulumi.Context, args GetZIAFirewallFilteringSourceIPGroupsOutputArgs, opts ...pulumi.InvokeOption) GetZIAFirewallFilteringSourceIPGroupsResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetZIAFirewallFilteringSourceIPGroupsResult, error) {
			args := v.(GetZIAFirewallFilteringSourceIPGroupsArgs)
			r, err := GetZIAFirewallFilteringSourceIPGroups(ctx, &args, opts...)
			var s GetZIAFirewallFilteringSourceIPGroupsResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetZIAFirewallFilteringSourceIPGroupsResultOutput)
}

// A collection of arguments for invoking getZIAFirewallFilteringSourceIPGroups.
type GetZIAFirewallFilteringSourceIPGroupsOutputArgs struct {
	// The ID of the ip source group resource.
	Id pulumi.IntPtrInput `pulumi:"id"`
	// The name of the ip source group to be exported.
	Name pulumi.StringPtrInput `pulumi:"name"`
}

func (GetZIAFirewallFilteringSourceIPGroupsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetZIAFirewallFilteringSourceIPGroupsArgs)(nil)).Elem()
}

// A collection of values returned by getZIAFirewallFilteringSourceIPGroups.
type GetZIAFirewallFilteringSourceIPGroupsResultOutput struct{ *pulumi.OutputState }

func (GetZIAFirewallFilteringSourceIPGroupsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetZIAFirewallFilteringSourceIPGroupsResult)(nil)).Elem()
}

func (o GetZIAFirewallFilteringSourceIPGroupsResultOutput) ToGetZIAFirewallFilteringSourceIPGroupsResultOutput() GetZIAFirewallFilteringSourceIPGroupsResultOutput {
	return o
}

func (o GetZIAFirewallFilteringSourceIPGroupsResultOutput) ToGetZIAFirewallFilteringSourceIPGroupsResultOutputWithContext(ctx context.Context) GetZIAFirewallFilteringSourceIPGroupsResultOutput {
	return o
}

// (String)
func (o GetZIAFirewallFilteringSourceIPGroupsResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v GetZIAFirewallFilteringSourceIPGroupsResult) string { return v.Description }).(pulumi.StringOutput)
}

// The ID of this resource.
func (o GetZIAFirewallFilteringSourceIPGroupsResultOutput) Id() pulumi.IntOutput {
	return o.ApplyT(func(v GetZIAFirewallFilteringSourceIPGroupsResult) int { return v.Id }).(pulumi.IntOutput)
}

// (List of String)
func (o GetZIAFirewallFilteringSourceIPGroupsResultOutput) IpAddresses() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetZIAFirewallFilteringSourceIPGroupsResult) []string { return v.IpAddresses }).(pulumi.StringArrayOutput)
}

func (o GetZIAFirewallFilteringSourceIPGroupsResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetZIAFirewallFilteringSourceIPGroupsResult) string { return v.Name }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetZIAFirewallFilteringSourceIPGroupsResultOutput{})
}
