// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package zia

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupZIASecuritySettings(ctx *pulumi.Context, opts ...pulumi.InvokeOption) (*LookupZIASecuritySettingsResult, error) {
	opts = pkgInvokeDefaultOpts(opts)
	var rv LookupZIASecuritySettingsResult
	err := ctx.Invoke("zia:index/getZIASecuritySettings:getZIASecuritySettings", nil, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of values returned by getZIASecuritySettings.
type LookupZIASecuritySettingsResult struct {
	BlacklistUrls []string `pulumi:"blacklistUrls"`
	// The provider-assigned unique ID for this managed resource.
	Id            string   `pulumi:"id"`
	WhitelistUrls []string `pulumi:"whitelistUrls"`
}
