// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package zia

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi-zia/sdk/go/zia"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := zia.LookupZIAActivationStatus(ctx, nil, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func LookupZIAActivationStatus(ctx *pulumi.Context, opts ...pulumi.InvokeOption) (*LookupZIAActivationStatusResult, error) {
	opts = pkgInvokeDefaultOpts(opts)
	var rv LookupZIAActivationStatusResult
	err := ctx.Invoke("zia:index/getZIAActivationStatus:getZIAActivationStatus", nil, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of values returned by getZIAActivationStatus.
type LookupZIAActivationStatusResult struct {
	// The provider-assigned unique ID for this managed resource.
	Id     string `pulumi:"id"`
	Status string `pulumi:"status"`
}
