// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package zia

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Use the **zia_device_groups** data source to get information about a device group in the Zscaler Internet Access cloud or via the API. This data source can then be associated with resources such as: URL Filtering Rules
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi-zia/sdk/go/zia"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := zia.GetZIADeviceGroups(ctx, &zia.GetZIADeviceGroupsArgs{
//				Name: pulumi.StringRef("IOS"),
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi-zia/sdk/go/zia"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := zia.GetZIADeviceGroups(ctx, &zia.GetZIADeviceGroupsArgs{
//				Name: pulumi.StringRef("Android"),
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func GetZIADeviceGroups(ctx *pulumi.Context, args *GetZIADeviceGroupsArgs, opts ...pulumi.InvokeOption) (*GetZIADeviceGroupsResult, error) {
	opts = pkgInvokeDefaultOpts(opts)
	var rv GetZIADeviceGroupsResult
	err := ctx.Invoke("zia:index/getZIADeviceGroups:getZIADeviceGroups", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getZIADeviceGroups.
type GetZIADeviceGroupsArgs struct {
	// The name of the device group to be exported.
	Name *string `pulumi:"name"`
}

// A collection of values returned by getZIADeviceGroups.
type GetZIADeviceGroupsResult struct {
	// (String) The device group's description.
	Description string `pulumi:"description"`
	// (int) The number of devices within the group.
	DeviceCount int `pulumi:"deviceCount"`
	// (String) The names of devices that belong to the device group. The device names are comma-separated.
	DeviceNames string `pulumi:"deviceNames"`
	// (String) The device group type. i.e ``ZCC_OS``, ``NON_ZCC``, ``CBI``
	GroupType string `pulumi:"groupType"`
	// (String) The unique identifer for the device group.
	Id int `pulumi:"id"`
	// (String) The device group name.
	Name *string `pulumi:"name"`
	// (String) The operating system (OS).
	OsType string `pulumi:"osType"`
	// (Boolean) Indicates whether this is a predefined device group. If this value is set to true, the group is predefined.
	Predefined bool `pulumi:"predefined"`
}

func GetZIADeviceGroupsOutput(ctx *pulumi.Context, args GetZIADeviceGroupsOutputArgs, opts ...pulumi.InvokeOption) GetZIADeviceGroupsResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetZIADeviceGroupsResult, error) {
			args := v.(GetZIADeviceGroupsArgs)
			r, err := GetZIADeviceGroups(ctx, &args, opts...)
			var s GetZIADeviceGroupsResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetZIADeviceGroupsResultOutput)
}

// A collection of arguments for invoking getZIADeviceGroups.
type GetZIADeviceGroupsOutputArgs struct {
	// The name of the device group to be exported.
	Name pulumi.StringPtrInput `pulumi:"name"`
}

func (GetZIADeviceGroupsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetZIADeviceGroupsArgs)(nil)).Elem()
}

// A collection of values returned by getZIADeviceGroups.
type GetZIADeviceGroupsResultOutput struct{ *pulumi.OutputState }

func (GetZIADeviceGroupsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetZIADeviceGroupsResult)(nil)).Elem()
}

func (o GetZIADeviceGroupsResultOutput) ToGetZIADeviceGroupsResultOutput() GetZIADeviceGroupsResultOutput {
	return o
}

func (o GetZIADeviceGroupsResultOutput) ToGetZIADeviceGroupsResultOutputWithContext(ctx context.Context) GetZIADeviceGroupsResultOutput {
	return o
}

// (String) The device group's description.
func (o GetZIADeviceGroupsResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v GetZIADeviceGroupsResult) string { return v.Description }).(pulumi.StringOutput)
}

// (int) The number of devices within the group.
func (o GetZIADeviceGroupsResultOutput) DeviceCount() pulumi.IntOutput {
	return o.ApplyT(func(v GetZIADeviceGroupsResult) int { return v.DeviceCount }).(pulumi.IntOutput)
}

// (String) The names of devices that belong to the device group. The device names are comma-separated.
func (o GetZIADeviceGroupsResultOutput) DeviceNames() pulumi.StringOutput {
	return o.ApplyT(func(v GetZIADeviceGroupsResult) string { return v.DeviceNames }).(pulumi.StringOutput)
}

// (String) The device group type. i.e “ZCC_OS“, “NON_ZCC“, “CBI“
func (o GetZIADeviceGroupsResultOutput) GroupType() pulumi.StringOutput {
	return o.ApplyT(func(v GetZIADeviceGroupsResult) string { return v.GroupType }).(pulumi.StringOutput)
}

// (String) The unique identifer for the device group.
func (o GetZIADeviceGroupsResultOutput) Id() pulumi.IntOutput {
	return o.ApplyT(func(v GetZIADeviceGroupsResult) int { return v.Id }).(pulumi.IntOutput)
}

// (String) The device group name.
func (o GetZIADeviceGroupsResultOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetZIADeviceGroupsResult) *string { return v.Name }).(pulumi.StringPtrOutput)
}

// (String) The operating system (OS).
func (o GetZIADeviceGroupsResultOutput) OsType() pulumi.StringOutput {
	return o.ApplyT(func(v GetZIADeviceGroupsResult) string { return v.OsType }).(pulumi.StringOutput)
}

// (Boolean) Indicates whether this is a predefined device group. If this value is set to true, the group is predefined.
func (o GetZIADeviceGroupsResultOutput) Predefined() pulumi.BoolOutput {
	return o.ApplyT(func(v GetZIADeviceGroupsResult) bool { return v.Predefined }).(pulumi.BoolOutput)
}

func init() {
	pulumi.RegisterOutputType(GetZIADeviceGroupsResultOutput{})
}
