// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package trafficforwarding

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type TrafficForwardingGRETunnelLastModifiedBy struct {
	Extensions map[string]string `pulumi:"extensions"`
	// Unique identifer of the GRE virtual IP address (VIP)
	Id   *int    `pulumi:"id"`
	Name *string `pulumi:"name"`
}

// TrafficForwardingGRETunnelLastModifiedByInput is an input type that accepts TrafficForwardingGRETunnelLastModifiedByArgs and TrafficForwardingGRETunnelLastModifiedByOutput values.
// You can construct a concrete instance of `TrafficForwardingGRETunnelLastModifiedByInput` via:
//
//	TrafficForwardingGRETunnelLastModifiedByArgs{...}
type TrafficForwardingGRETunnelLastModifiedByInput interface {
	pulumi.Input

	ToTrafficForwardingGRETunnelLastModifiedByOutput() TrafficForwardingGRETunnelLastModifiedByOutput
	ToTrafficForwardingGRETunnelLastModifiedByOutputWithContext(context.Context) TrafficForwardingGRETunnelLastModifiedByOutput
}

type TrafficForwardingGRETunnelLastModifiedByArgs struct {
	Extensions pulumi.StringMapInput `pulumi:"extensions"`
	// Unique identifer of the GRE virtual IP address (VIP)
	Id   pulumi.IntPtrInput    `pulumi:"id"`
	Name pulumi.StringPtrInput `pulumi:"name"`
}

func (TrafficForwardingGRETunnelLastModifiedByArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*TrafficForwardingGRETunnelLastModifiedBy)(nil)).Elem()
}

func (i TrafficForwardingGRETunnelLastModifiedByArgs) ToTrafficForwardingGRETunnelLastModifiedByOutput() TrafficForwardingGRETunnelLastModifiedByOutput {
	return i.ToTrafficForwardingGRETunnelLastModifiedByOutputWithContext(context.Background())
}

func (i TrafficForwardingGRETunnelLastModifiedByArgs) ToTrafficForwardingGRETunnelLastModifiedByOutputWithContext(ctx context.Context) TrafficForwardingGRETunnelLastModifiedByOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TrafficForwardingGRETunnelLastModifiedByOutput)
}

// TrafficForwardingGRETunnelLastModifiedByArrayInput is an input type that accepts TrafficForwardingGRETunnelLastModifiedByArray and TrafficForwardingGRETunnelLastModifiedByArrayOutput values.
// You can construct a concrete instance of `TrafficForwardingGRETunnelLastModifiedByArrayInput` via:
//
//	TrafficForwardingGRETunnelLastModifiedByArray{ TrafficForwardingGRETunnelLastModifiedByArgs{...} }
type TrafficForwardingGRETunnelLastModifiedByArrayInput interface {
	pulumi.Input

	ToTrafficForwardingGRETunnelLastModifiedByArrayOutput() TrafficForwardingGRETunnelLastModifiedByArrayOutput
	ToTrafficForwardingGRETunnelLastModifiedByArrayOutputWithContext(context.Context) TrafficForwardingGRETunnelLastModifiedByArrayOutput
}

type TrafficForwardingGRETunnelLastModifiedByArray []TrafficForwardingGRETunnelLastModifiedByInput

func (TrafficForwardingGRETunnelLastModifiedByArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]TrafficForwardingGRETunnelLastModifiedBy)(nil)).Elem()
}

func (i TrafficForwardingGRETunnelLastModifiedByArray) ToTrafficForwardingGRETunnelLastModifiedByArrayOutput() TrafficForwardingGRETunnelLastModifiedByArrayOutput {
	return i.ToTrafficForwardingGRETunnelLastModifiedByArrayOutputWithContext(context.Background())
}

func (i TrafficForwardingGRETunnelLastModifiedByArray) ToTrafficForwardingGRETunnelLastModifiedByArrayOutputWithContext(ctx context.Context) TrafficForwardingGRETunnelLastModifiedByArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TrafficForwardingGRETunnelLastModifiedByArrayOutput)
}

type TrafficForwardingGRETunnelLastModifiedByOutput struct{ *pulumi.OutputState }

func (TrafficForwardingGRETunnelLastModifiedByOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*TrafficForwardingGRETunnelLastModifiedBy)(nil)).Elem()
}

func (o TrafficForwardingGRETunnelLastModifiedByOutput) ToTrafficForwardingGRETunnelLastModifiedByOutput() TrafficForwardingGRETunnelLastModifiedByOutput {
	return o
}

func (o TrafficForwardingGRETunnelLastModifiedByOutput) ToTrafficForwardingGRETunnelLastModifiedByOutputWithContext(ctx context.Context) TrafficForwardingGRETunnelLastModifiedByOutput {
	return o
}

func (o TrafficForwardingGRETunnelLastModifiedByOutput) Extensions() pulumi.StringMapOutput {
	return o.ApplyT(func(v TrafficForwardingGRETunnelLastModifiedBy) map[string]string { return v.Extensions }).(pulumi.StringMapOutput)
}

// Unique identifer of the GRE virtual IP address (VIP)
func (o TrafficForwardingGRETunnelLastModifiedByOutput) Id() pulumi.IntPtrOutput {
	return o.ApplyT(func(v TrafficForwardingGRETunnelLastModifiedBy) *int { return v.Id }).(pulumi.IntPtrOutput)
}

func (o TrafficForwardingGRETunnelLastModifiedByOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v TrafficForwardingGRETunnelLastModifiedBy) *string { return v.Name }).(pulumi.StringPtrOutput)
}

type TrafficForwardingGRETunnelLastModifiedByArrayOutput struct{ *pulumi.OutputState }

func (TrafficForwardingGRETunnelLastModifiedByArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]TrafficForwardingGRETunnelLastModifiedBy)(nil)).Elem()
}

func (o TrafficForwardingGRETunnelLastModifiedByArrayOutput) ToTrafficForwardingGRETunnelLastModifiedByArrayOutput() TrafficForwardingGRETunnelLastModifiedByArrayOutput {
	return o
}

func (o TrafficForwardingGRETunnelLastModifiedByArrayOutput) ToTrafficForwardingGRETunnelLastModifiedByArrayOutputWithContext(ctx context.Context) TrafficForwardingGRETunnelLastModifiedByArrayOutput {
	return o
}

func (o TrafficForwardingGRETunnelLastModifiedByArrayOutput) Index(i pulumi.IntInput) TrafficForwardingGRETunnelLastModifiedByOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) TrafficForwardingGRETunnelLastModifiedBy {
		return vs[0].([]TrafficForwardingGRETunnelLastModifiedBy)[vs[1].(int)]
	}).(TrafficForwardingGRETunnelLastModifiedByOutput)
}

type TrafficForwardingGRETunnelPrimaryDestVip struct {
	Datacenter *string `pulumi:"datacenter"`
	// Unique identifer of the GRE virtual IP address (VIP)
	Id                 *int  `pulumi:"id"`
	PrivateServiceEdge *bool `pulumi:"privateServiceEdge"`
	// GRE cluster virtual IP address (VIP)
	VirtualIp *string `pulumi:"virtualIp"`
}

// TrafficForwardingGRETunnelPrimaryDestVipInput is an input type that accepts TrafficForwardingGRETunnelPrimaryDestVipArgs and TrafficForwardingGRETunnelPrimaryDestVipOutput values.
// You can construct a concrete instance of `TrafficForwardingGRETunnelPrimaryDestVipInput` via:
//
//	TrafficForwardingGRETunnelPrimaryDestVipArgs{...}
type TrafficForwardingGRETunnelPrimaryDestVipInput interface {
	pulumi.Input

	ToTrafficForwardingGRETunnelPrimaryDestVipOutput() TrafficForwardingGRETunnelPrimaryDestVipOutput
	ToTrafficForwardingGRETunnelPrimaryDestVipOutputWithContext(context.Context) TrafficForwardingGRETunnelPrimaryDestVipOutput
}

type TrafficForwardingGRETunnelPrimaryDestVipArgs struct {
	Datacenter pulumi.StringPtrInput `pulumi:"datacenter"`
	// Unique identifer of the GRE virtual IP address (VIP)
	Id                 pulumi.IntPtrInput  `pulumi:"id"`
	PrivateServiceEdge pulumi.BoolPtrInput `pulumi:"privateServiceEdge"`
	// GRE cluster virtual IP address (VIP)
	VirtualIp pulumi.StringPtrInput `pulumi:"virtualIp"`
}

func (TrafficForwardingGRETunnelPrimaryDestVipArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*TrafficForwardingGRETunnelPrimaryDestVip)(nil)).Elem()
}

func (i TrafficForwardingGRETunnelPrimaryDestVipArgs) ToTrafficForwardingGRETunnelPrimaryDestVipOutput() TrafficForwardingGRETunnelPrimaryDestVipOutput {
	return i.ToTrafficForwardingGRETunnelPrimaryDestVipOutputWithContext(context.Background())
}

func (i TrafficForwardingGRETunnelPrimaryDestVipArgs) ToTrafficForwardingGRETunnelPrimaryDestVipOutputWithContext(ctx context.Context) TrafficForwardingGRETunnelPrimaryDestVipOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TrafficForwardingGRETunnelPrimaryDestVipOutput)
}

// TrafficForwardingGRETunnelPrimaryDestVipArrayInput is an input type that accepts TrafficForwardingGRETunnelPrimaryDestVipArray and TrafficForwardingGRETunnelPrimaryDestVipArrayOutput values.
// You can construct a concrete instance of `TrafficForwardingGRETunnelPrimaryDestVipArrayInput` via:
//
//	TrafficForwardingGRETunnelPrimaryDestVipArray{ TrafficForwardingGRETunnelPrimaryDestVipArgs{...} }
type TrafficForwardingGRETunnelPrimaryDestVipArrayInput interface {
	pulumi.Input

	ToTrafficForwardingGRETunnelPrimaryDestVipArrayOutput() TrafficForwardingGRETunnelPrimaryDestVipArrayOutput
	ToTrafficForwardingGRETunnelPrimaryDestVipArrayOutputWithContext(context.Context) TrafficForwardingGRETunnelPrimaryDestVipArrayOutput
}

type TrafficForwardingGRETunnelPrimaryDestVipArray []TrafficForwardingGRETunnelPrimaryDestVipInput

func (TrafficForwardingGRETunnelPrimaryDestVipArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]TrafficForwardingGRETunnelPrimaryDestVip)(nil)).Elem()
}

func (i TrafficForwardingGRETunnelPrimaryDestVipArray) ToTrafficForwardingGRETunnelPrimaryDestVipArrayOutput() TrafficForwardingGRETunnelPrimaryDestVipArrayOutput {
	return i.ToTrafficForwardingGRETunnelPrimaryDestVipArrayOutputWithContext(context.Background())
}

func (i TrafficForwardingGRETunnelPrimaryDestVipArray) ToTrafficForwardingGRETunnelPrimaryDestVipArrayOutputWithContext(ctx context.Context) TrafficForwardingGRETunnelPrimaryDestVipArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TrafficForwardingGRETunnelPrimaryDestVipArrayOutput)
}

type TrafficForwardingGRETunnelPrimaryDestVipOutput struct{ *pulumi.OutputState }

func (TrafficForwardingGRETunnelPrimaryDestVipOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*TrafficForwardingGRETunnelPrimaryDestVip)(nil)).Elem()
}

func (o TrafficForwardingGRETunnelPrimaryDestVipOutput) ToTrafficForwardingGRETunnelPrimaryDestVipOutput() TrafficForwardingGRETunnelPrimaryDestVipOutput {
	return o
}

func (o TrafficForwardingGRETunnelPrimaryDestVipOutput) ToTrafficForwardingGRETunnelPrimaryDestVipOutputWithContext(ctx context.Context) TrafficForwardingGRETunnelPrimaryDestVipOutput {
	return o
}

func (o TrafficForwardingGRETunnelPrimaryDestVipOutput) Datacenter() pulumi.StringPtrOutput {
	return o.ApplyT(func(v TrafficForwardingGRETunnelPrimaryDestVip) *string { return v.Datacenter }).(pulumi.StringPtrOutput)
}

// Unique identifer of the GRE virtual IP address (VIP)
func (o TrafficForwardingGRETunnelPrimaryDestVipOutput) Id() pulumi.IntPtrOutput {
	return o.ApplyT(func(v TrafficForwardingGRETunnelPrimaryDestVip) *int { return v.Id }).(pulumi.IntPtrOutput)
}

func (o TrafficForwardingGRETunnelPrimaryDestVipOutput) PrivateServiceEdge() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v TrafficForwardingGRETunnelPrimaryDestVip) *bool { return v.PrivateServiceEdge }).(pulumi.BoolPtrOutput)
}

// GRE cluster virtual IP address (VIP)
func (o TrafficForwardingGRETunnelPrimaryDestVipOutput) VirtualIp() pulumi.StringPtrOutput {
	return o.ApplyT(func(v TrafficForwardingGRETunnelPrimaryDestVip) *string { return v.VirtualIp }).(pulumi.StringPtrOutput)
}

type TrafficForwardingGRETunnelPrimaryDestVipArrayOutput struct{ *pulumi.OutputState }

func (TrafficForwardingGRETunnelPrimaryDestVipArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]TrafficForwardingGRETunnelPrimaryDestVip)(nil)).Elem()
}

func (o TrafficForwardingGRETunnelPrimaryDestVipArrayOutput) ToTrafficForwardingGRETunnelPrimaryDestVipArrayOutput() TrafficForwardingGRETunnelPrimaryDestVipArrayOutput {
	return o
}

func (o TrafficForwardingGRETunnelPrimaryDestVipArrayOutput) ToTrafficForwardingGRETunnelPrimaryDestVipArrayOutputWithContext(ctx context.Context) TrafficForwardingGRETunnelPrimaryDestVipArrayOutput {
	return o
}

func (o TrafficForwardingGRETunnelPrimaryDestVipArrayOutput) Index(i pulumi.IntInput) TrafficForwardingGRETunnelPrimaryDestVipOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) TrafficForwardingGRETunnelPrimaryDestVip {
		return vs[0].([]TrafficForwardingGRETunnelPrimaryDestVip)[vs[1].(int)]
	}).(TrafficForwardingGRETunnelPrimaryDestVipOutput)
}

type TrafficForwardingGRETunnelSecondaryDestVip struct {
	Datacenter *string `pulumi:"datacenter"`
	// Unique identifer of the GRE virtual IP address (VIP)
	Id                 *int  `pulumi:"id"`
	PrivateServiceEdge *bool `pulumi:"privateServiceEdge"`
	// GRE cluster virtual IP address (VIP)
	VirtualIp *string `pulumi:"virtualIp"`
}

// TrafficForwardingGRETunnelSecondaryDestVipInput is an input type that accepts TrafficForwardingGRETunnelSecondaryDestVipArgs and TrafficForwardingGRETunnelSecondaryDestVipOutput values.
// You can construct a concrete instance of `TrafficForwardingGRETunnelSecondaryDestVipInput` via:
//
//	TrafficForwardingGRETunnelSecondaryDestVipArgs{...}
type TrafficForwardingGRETunnelSecondaryDestVipInput interface {
	pulumi.Input

	ToTrafficForwardingGRETunnelSecondaryDestVipOutput() TrafficForwardingGRETunnelSecondaryDestVipOutput
	ToTrafficForwardingGRETunnelSecondaryDestVipOutputWithContext(context.Context) TrafficForwardingGRETunnelSecondaryDestVipOutput
}

type TrafficForwardingGRETunnelSecondaryDestVipArgs struct {
	Datacenter pulumi.StringPtrInput `pulumi:"datacenter"`
	// Unique identifer of the GRE virtual IP address (VIP)
	Id                 pulumi.IntPtrInput  `pulumi:"id"`
	PrivateServiceEdge pulumi.BoolPtrInput `pulumi:"privateServiceEdge"`
	// GRE cluster virtual IP address (VIP)
	VirtualIp pulumi.StringPtrInput `pulumi:"virtualIp"`
}

func (TrafficForwardingGRETunnelSecondaryDestVipArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*TrafficForwardingGRETunnelSecondaryDestVip)(nil)).Elem()
}

func (i TrafficForwardingGRETunnelSecondaryDestVipArgs) ToTrafficForwardingGRETunnelSecondaryDestVipOutput() TrafficForwardingGRETunnelSecondaryDestVipOutput {
	return i.ToTrafficForwardingGRETunnelSecondaryDestVipOutputWithContext(context.Background())
}

func (i TrafficForwardingGRETunnelSecondaryDestVipArgs) ToTrafficForwardingGRETunnelSecondaryDestVipOutputWithContext(ctx context.Context) TrafficForwardingGRETunnelSecondaryDestVipOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TrafficForwardingGRETunnelSecondaryDestVipOutput)
}

// TrafficForwardingGRETunnelSecondaryDestVipArrayInput is an input type that accepts TrafficForwardingGRETunnelSecondaryDestVipArray and TrafficForwardingGRETunnelSecondaryDestVipArrayOutput values.
// You can construct a concrete instance of `TrafficForwardingGRETunnelSecondaryDestVipArrayInput` via:
//
//	TrafficForwardingGRETunnelSecondaryDestVipArray{ TrafficForwardingGRETunnelSecondaryDestVipArgs{...} }
type TrafficForwardingGRETunnelSecondaryDestVipArrayInput interface {
	pulumi.Input

	ToTrafficForwardingGRETunnelSecondaryDestVipArrayOutput() TrafficForwardingGRETunnelSecondaryDestVipArrayOutput
	ToTrafficForwardingGRETunnelSecondaryDestVipArrayOutputWithContext(context.Context) TrafficForwardingGRETunnelSecondaryDestVipArrayOutput
}

type TrafficForwardingGRETunnelSecondaryDestVipArray []TrafficForwardingGRETunnelSecondaryDestVipInput

func (TrafficForwardingGRETunnelSecondaryDestVipArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]TrafficForwardingGRETunnelSecondaryDestVip)(nil)).Elem()
}

func (i TrafficForwardingGRETunnelSecondaryDestVipArray) ToTrafficForwardingGRETunnelSecondaryDestVipArrayOutput() TrafficForwardingGRETunnelSecondaryDestVipArrayOutput {
	return i.ToTrafficForwardingGRETunnelSecondaryDestVipArrayOutputWithContext(context.Background())
}

func (i TrafficForwardingGRETunnelSecondaryDestVipArray) ToTrafficForwardingGRETunnelSecondaryDestVipArrayOutputWithContext(ctx context.Context) TrafficForwardingGRETunnelSecondaryDestVipArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TrafficForwardingGRETunnelSecondaryDestVipArrayOutput)
}

type TrafficForwardingGRETunnelSecondaryDestVipOutput struct{ *pulumi.OutputState }

func (TrafficForwardingGRETunnelSecondaryDestVipOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*TrafficForwardingGRETunnelSecondaryDestVip)(nil)).Elem()
}

func (o TrafficForwardingGRETunnelSecondaryDestVipOutput) ToTrafficForwardingGRETunnelSecondaryDestVipOutput() TrafficForwardingGRETunnelSecondaryDestVipOutput {
	return o
}

func (o TrafficForwardingGRETunnelSecondaryDestVipOutput) ToTrafficForwardingGRETunnelSecondaryDestVipOutputWithContext(ctx context.Context) TrafficForwardingGRETunnelSecondaryDestVipOutput {
	return o
}

func (o TrafficForwardingGRETunnelSecondaryDestVipOutput) Datacenter() pulumi.StringPtrOutput {
	return o.ApplyT(func(v TrafficForwardingGRETunnelSecondaryDestVip) *string { return v.Datacenter }).(pulumi.StringPtrOutput)
}

// Unique identifer of the GRE virtual IP address (VIP)
func (o TrafficForwardingGRETunnelSecondaryDestVipOutput) Id() pulumi.IntPtrOutput {
	return o.ApplyT(func(v TrafficForwardingGRETunnelSecondaryDestVip) *int { return v.Id }).(pulumi.IntPtrOutput)
}

func (o TrafficForwardingGRETunnelSecondaryDestVipOutput) PrivateServiceEdge() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v TrafficForwardingGRETunnelSecondaryDestVip) *bool { return v.PrivateServiceEdge }).(pulumi.BoolPtrOutput)
}

// GRE cluster virtual IP address (VIP)
func (o TrafficForwardingGRETunnelSecondaryDestVipOutput) VirtualIp() pulumi.StringPtrOutput {
	return o.ApplyT(func(v TrafficForwardingGRETunnelSecondaryDestVip) *string { return v.VirtualIp }).(pulumi.StringPtrOutput)
}

type TrafficForwardingGRETunnelSecondaryDestVipArrayOutput struct{ *pulumi.OutputState }

func (TrafficForwardingGRETunnelSecondaryDestVipArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]TrafficForwardingGRETunnelSecondaryDestVip)(nil)).Elem()
}

func (o TrafficForwardingGRETunnelSecondaryDestVipArrayOutput) ToTrafficForwardingGRETunnelSecondaryDestVipArrayOutput() TrafficForwardingGRETunnelSecondaryDestVipArrayOutput {
	return o
}

func (o TrafficForwardingGRETunnelSecondaryDestVipArrayOutput) ToTrafficForwardingGRETunnelSecondaryDestVipArrayOutputWithContext(ctx context.Context) TrafficForwardingGRETunnelSecondaryDestVipArrayOutput {
	return o
}

func (o TrafficForwardingGRETunnelSecondaryDestVipArrayOutput) Index(i pulumi.IntInput) TrafficForwardingGRETunnelSecondaryDestVipOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) TrafficForwardingGRETunnelSecondaryDestVip {
		return vs[0].([]TrafficForwardingGRETunnelSecondaryDestVip)[vs[1].(int)]
	}).(TrafficForwardingGRETunnelSecondaryDestVipOutput)
}

type TrafficForwardingStaticIPLastModifiedBy struct {
	Extensions map[string]string `pulumi:"extensions"`
	Id         *int              `pulumi:"id"`
	Name       *string           `pulumi:"name"`
}

// TrafficForwardingStaticIPLastModifiedByInput is an input type that accepts TrafficForwardingStaticIPLastModifiedByArgs and TrafficForwardingStaticIPLastModifiedByOutput values.
// You can construct a concrete instance of `TrafficForwardingStaticIPLastModifiedByInput` via:
//
//	TrafficForwardingStaticIPLastModifiedByArgs{...}
type TrafficForwardingStaticIPLastModifiedByInput interface {
	pulumi.Input

	ToTrafficForwardingStaticIPLastModifiedByOutput() TrafficForwardingStaticIPLastModifiedByOutput
	ToTrafficForwardingStaticIPLastModifiedByOutputWithContext(context.Context) TrafficForwardingStaticIPLastModifiedByOutput
}

type TrafficForwardingStaticIPLastModifiedByArgs struct {
	Extensions pulumi.StringMapInput `pulumi:"extensions"`
	Id         pulumi.IntPtrInput    `pulumi:"id"`
	Name       pulumi.StringPtrInput `pulumi:"name"`
}

func (TrafficForwardingStaticIPLastModifiedByArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*TrafficForwardingStaticIPLastModifiedBy)(nil)).Elem()
}

func (i TrafficForwardingStaticIPLastModifiedByArgs) ToTrafficForwardingStaticIPLastModifiedByOutput() TrafficForwardingStaticIPLastModifiedByOutput {
	return i.ToTrafficForwardingStaticIPLastModifiedByOutputWithContext(context.Background())
}

func (i TrafficForwardingStaticIPLastModifiedByArgs) ToTrafficForwardingStaticIPLastModifiedByOutputWithContext(ctx context.Context) TrafficForwardingStaticIPLastModifiedByOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TrafficForwardingStaticIPLastModifiedByOutput)
}

// TrafficForwardingStaticIPLastModifiedByArrayInput is an input type that accepts TrafficForwardingStaticIPLastModifiedByArray and TrafficForwardingStaticIPLastModifiedByArrayOutput values.
// You can construct a concrete instance of `TrafficForwardingStaticIPLastModifiedByArrayInput` via:
//
//	TrafficForwardingStaticIPLastModifiedByArray{ TrafficForwardingStaticIPLastModifiedByArgs{...} }
type TrafficForwardingStaticIPLastModifiedByArrayInput interface {
	pulumi.Input

	ToTrafficForwardingStaticIPLastModifiedByArrayOutput() TrafficForwardingStaticIPLastModifiedByArrayOutput
	ToTrafficForwardingStaticIPLastModifiedByArrayOutputWithContext(context.Context) TrafficForwardingStaticIPLastModifiedByArrayOutput
}

type TrafficForwardingStaticIPLastModifiedByArray []TrafficForwardingStaticIPLastModifiedByInput

func (TrafficForwardingStaticIPLastModifiedByArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]TrafficForwardingStaticIPLastModifiedBy)(nil)).Elem()
}

func (i TrafficForwardingStaticIPLastModifiedByArray) ToTrafficForwardingStaticIPLastModifiedByArrayOutput() TrafficForwardingStaticIPLastModifiedByArrayOutput {
	return i.ToTrafficForwardingStaticIPLastModifiedByArrayOutputWithContext(context.Background())
}

func (i TrafficForwardingStaticIPLastModifiedByArray) ToTrafficForwardingStaticIPLastModifiedByArrayOutputWithContext(ctx context.Context) TrafficForwardingStaticIPLastModifiedByArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TrafficForwardingStaticIPLastModifiedByArrayOutput)
}

type TrafficForwardingStaticIPLastModifiedByOutput struct{ *pulumi.OutputState }

func (TrafficForwardingStaticIPLastModifiedByOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*TrafficForwardingStaticIPLastModifiedBy)(nil)).Elem()
}

func (o TrafficForwardingStaticIPLastModifiedByOutput) ToTrafficForwardingStaticIPLastModifiedByOutput() TrafficForwardingStaticIPLastModifiedByOutput {
	return o
}

func (o TrafficForwardingStaticIPLastModifiedByOutput) ToTrafficForwardingStaticIPLastModifiedByOutputWithContext(ctx context.Context) TrafficForwardingStaticIPLastModifiedByOutput {
	return o
}

func (o TrafficForwardingStaticIPLastModifiedByOutput) Extensions() pulumi.StringMapOutput {
	return o.ApplyT(func(v TrafficForwardingStaticIPLastModifiedBy) map[string]string { return v.Extensions }).(pulumi.StringMapOutput)
}

func (o TrafficForwardingStaticIPLastModifiedByOutput) Id() pulumi.IntPtrOutput {
	return o.ApplyT(func(v TrafficForwardingStaticIPLastModifiedBy) *int { return v.Id }).(pulumi.IntPtrOutput)
}

func (o TrafficForwardingStaticIPLastModifiedByOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v TrafficForwardingStaticIPLastModifiedBy) *string { return v.Name }).(pulumi.StringPtrOutput)
}

type TrafficForwardingStaticIPLastModifiedByArrayOutput struct{ *pulumi.OutputState }

func (TrafficForwardingStaticIPLastModifiedByArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]TrafficForwardingStaticIPLastModifiedBy)(nil)).Elem()
}

func (o TrafficForwardingStaticIPLastModifiedByArrayOutput) ToTrafficForwardingStaticIPLastModifiedByArrayOutput() TrafficForwardingStaticIPLastModifiedByArrayOutput {
	return o
}

func (o TrafficForwardingStaticIPLastModifiedByArrayOutput) ToTrafficForwardingStaticIPLastModifiedByArrayOutputWithContext(ctx context.Context) TrafficForwardingStaticIPLastModifiedByArrayOutput {
	return o
}

func (o TrafficForwardingStaticIPLastModifiedByArrayOutput) Index(i pulumi.IntInput) TrafficForwardingStaticIPLastModifiedByOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) TrafficForwardingStaticIPLastModifiedBy {
		return vs[0].([]TrafficForwardingStaticIPLastModifiedBy)[vs[1].(int)]
	}).(TrafficForwardingStaticIPLastModifiedByOutput)
}

type TrafficForwardingStaticIPManagedBy struct {
	Extensions map[string]string `pulumi:"extensions"`
	Id         *int              `pulumi:"id"`
	Name       *string           `pulumi:"name"`
}

// TrafficForwardingStaticIPManagedByInput is an input type that accepts TrafficForwardingStaticIPManagedByArgs and TrafficForwardingStaticIPManagedByOutput values.
// You can construct a concrete instance of `TrafficForwardingStaticIPManagedByInput` via:
//
//	TrafficForwardingStaticIPManagedByArgs{...}
type TrafficForwardingStaticIPManagedByInput interface {
	pulumi.Input

	ToTrafficForwardingStaticIPManagedByOutput() TrafficForwardingStaticIPManagedByOutput
	ToTrafficForwardingStaticIPManagedByOutputWithContext(context.Context) TrafficForwardingStaticIPManagedByOutput
}

type TrafficForwardingStaticIPManagedByArgs struct {
	Extensions pulumi.StringMapInput `pulumi:"extensions"`
	Id         pulumi.IntPtrInput    `pulumi:"id"`
	Name       pulumi.StringPtrInput `pulumi:"name"`
}

func (TrafficForwardingStaticIPManagedByArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*TrafficForwardingStaticIPManagedBy)(nil)).Elem()
}

func (i TrafficForwardingStaticIPManagedByArgs) ToTrafficForwardingStaticIPManagedByOutput() TrafficForwardingStaticIPManagedByOutput {
	return i.ToTrafficForwardingStaticIPManagedByOutputWithContext(context.Background())
}

func (i TrafficForwardingStaticIPManagedByArgs) ToTrafficForwardingStaticIPManagedByOutputWithContext(ctx context.Context) TrafficForwardingStaticIPManagedByOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TrafficForwardingStaticIPManagedByOutput)
}

// TrafficForwardingStaticIPManagedByArrayInput is an input type that accepts TrafficForwardingStaticIPManagedByArray and TrafficForwardingStaticIPManagedByArrayOutput values.
// You can construct a concrete instance of `TrafficForwardingStaticIPManagedByArrayInput` via:
//
//	TrafficForwardingStaticIPManagedByArray{ TrafficForwardingStaticIPManagedByArgs{...} }
type TrafficForwardingStaticIPManagedByArrayInput interface {
	pulumi.Input

	ToTrafficForwardingStaticIPManagedByArrayOutput() TrafficForwardingStaticIPManagedByArrayOutput
	ToTrafficForwardingStaticIPManagedByArrayOutputWithContext(context.Context) TrafficForwardingStaticIPManagedByArrayOutput
}

type TrafficForwardingStaticIPManagedByArray []TrafficForwardingStaticIPManagedByInput

func (TrafficForwardingStaticIPManagedByArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]TrafficForwardingStaticIPManagedBy)(nil)).Elem()
}

func (i TrafficForwardingStaticIPManagedByArray) ToTrafficForwardingStaticIPManagedByArrayOutput() TrafficForwardingStaticIPManagedByArrayOutput {
	return i.ToTrafficForwardingStaticIPManagedByArrayOutputWithContext(context.Background())
}

func (i TrafficForwardingStaticIPManagedByArray) ToTrafficForwardingStaticIPManagedByArrayOutputWithContext(ctx context.Context) TrafficForwardingStaticIPManagedByArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TrafficForwardingStaticIPManagedByArrayOutput)
}

type TrafficForwardingStaticIPManagedByOutput struct{ *pulumi.OutputState }

func (TrafficForwardingStaticIPManagedByOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*TrafficForwardingStaticIPManagedBy)(nil)).Elem()
}

func (o TrafficForwardingStaticIPManagedByOutput) ToTrafficForwardingStaticIPManagedByOutput() TrafficForwardingStaticIPManagedByOutput {
	return o
}

func (o TrafficForwardingStaticIPManagedByOutput) ToTrafficForwardingStaticIPManagedByOutputWithContext(ctx context.Context) TrafficForwardingStaticIPManagedByOutput {
	return o
}

func (o TrafficForwardingStaticIPManagedByOutput) Extensions() pulumi.StringMapOutput {
	return o.ApplyT(func(v TrafficForwardingStaticIPManagedBy) map[string]string { return v.Extensions }).(pulumi.StringMapOutput)
}

func (o TrafficForwardingStaticIPManagedByOutput) Id() pulumi.IntPtrOutput {
	return o.ApplyT(func(v TrafficForwardingStaticIPManagedBy) *int { return v.Id }).(pulumi.IntPtrOutput)
}

func (o TrafficForwardingStaticIPManagedByOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v TrafficForwardingStaticIPManagedBy) *string { return v.Name }).(pulumi.StringPtrOutput)
}

type TrafficForwardingStaticIPManagedByArrayOutput struct{ *pulumi.OutputState }

func (TrafficForwardingStaticIPManagedByArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]TrafficForwardingStaticIPManagedBy)(nil)).Elem()
}

func (o TrafficForwardingStaticIPManagedByArrayOutput) ToTrafficForwardingStaticIPManagedByArrayOutput() TrafficForwardingStaticIPManagedByArrayOutput {
	return o
}

func (o TrafficForwardingStaticIPManagedByArrayOutput) ToTrafficForwardingStaticIPManagedByArrayOutputWithContext(ctx context.Context) TrafficForwardingStaticIPManagedByArrayOutput {
	return o
}

func (o TrafficForwardingStaticIPManagedByArrayOutput) Index(i pulumi.IntInput) TrafficForwardingStaticIPManagedByOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) TrafficForwardingStaticIPManagedBy {
		return vs[0].([]TrafficForwardingStaticIPManagedBy)[vs[1].(int)]
	}).(TrafficForwardingStaticIPManagedByOutput)
}

type GetTrafficForwardingGREInternalIPRangeList struct {
	EndIpAddress   string `pulumi:"endIpAddress"`
	StartIpAddress string `pulumi:"startIpAddress"`
}

// GetTrafficForwardingGREInternalIPRangeListInput is an input type that accepts GetTrafficForwardingGREInternalIPRangeListArgs and GetTrafficForwardingGREInternalIPRangeListOutput values.
// You can construct a concrete instance of `GetTrafficForwardingGREInternalIPRangeListInput` via:
//
//	GetTrafficForwardingGREInternalIPRangeListArgs{...}
type GetTrafficForwardingGREInternalIPRangeListInput interface {
	pulumi.Input

	ToGetTrafficForwardingGREInternalIPRangeListOutput() GetTrafficForwardingGREInternalIPRangeListOutput
	ToGetTrafficForwardingGREInternalIPRangeListOutputWithContext(context.Context) GetTrafficForwardingGREInternalIPRangeListOutput
}

type GetTrafficForwardingGREInternalIPRangeListArgs struct {
	EndIpAddress   pulumi.StringInput `pulumi:"endIpAddress"`
	StartIpAddress pulumi.StringInput `pulumi:"startIpAddress"`
}

func (GetTrafficForwardingGREInternalIPRangeListArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetTrafficForwardingGREInternalIPRangeList)(nil)).Elem()
}

func (i GetTrafficForwardingGREInternalIPRangeListArgs) ToGetTrafficForwardingGREInternalIPRangeListOutput() GetTrafficForwardingGREInternalIPRangeListOutput {
	return i.ToGetTrafficForwardingGREInternalIPRangeListOutputWithContext(context.Background())
}

func (i GetTrafficForwardingGREInternalIPRangeListArgs) ToGetTrafficForwardingGREInternalIPRangeListOutputWithContext(ctx context.Context) GetTrafficForwardingGREInternalIPRangeListOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetTrafficForwardingGREInternalIPRangeListOutput)
}

// GetTrafficForwardingGREInternalIPRangeListArrayInput is an input type that accepts GetTrafficForwardingGREInternalIPRangeListArray and GetTrafficForwardingGREInternalIPRangeListArrayOutput values.
// You can construct a concrete instance of `GetTrafficForwardingGREInternalIPRangeListArrayInput` via:
//
//	GetTrafficForwardingGREInternalIPRangeListArray{ GetTrafficForwardingGREInternalIPRangeListArgs{...} }
type GetTrafficForwardingGREInternalIPRangeListArrayInput interface {
	pulumi.Input

	ToGetTrafficForwardingGREInternalIPRangeListArrayOutput() GetTrafficForwardingGREInternalIPRangeListArrayOutput
	ToGetTrafficForwardingGREInternalIPRangeListArrayOutputWithContext(context.Context) GetTrafficForwardingGREInternalIPRangeListArrayOutput
}

type GetTrafficForwardingGREInternalIPRangeListArray []GetTrafficForwardingGREInternalIPRangeListInput

func (GetTrafficForwardingGREInternalIPRangeListArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetTrafficForwardingGREInternalIPRangeList)(nil)).Elem()
}

func (i GetTrafficForwardingGREInternalIPRangeListArray) ToGetTrafficForwardingGREInternalIPRangeListArrayOutput() GetTrafficForwardingGREInternalIPRangeListArrayOutput {
	return i.ToGetTrafficForwardingGREInternalIPRangeListArrayOutputWithContext(context.Background())
}

func (i GetTrafficForwardingGREInternalIPRangeListArray) ToGetTrafficForwardingGREInternalIPRangeListArrayOutputWithContext(ctx context.Context) GetTrafficForwardingGREInternalIPRangeListArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetTrafficForwardingGREInternalIPRangeListArrayOutput)
}

type GetTrafficForwardingGREInternalIPRangeListOutput struct{ *pulumi.OutputState }

func (GetTrafficForwardingGREInternalIPRangeListOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetTrafficForwardingGREInternalIPRangeList)(nil)).Elem()
}

func (o GetTrafficForwardingGREInternalIPRangeListOutput) ToGetTrafficForwardingGREInternalIPRangeListOutput() GetTrafficForwardingGREInternalIPRangeListOutput {
	return o
}

func (o GetTrafficForwardingGREInternalIPRangeListOutput) ToGetTrafficForwardingGREInternalIPRangeListOutputWithContext(ctx context.Context) GetTrafficForwardingGREInternalIPRangeListOutput {
	return o
}

func (o GetTrafficForwardingGREInternalIPRangeListOutput) EndIpAddress() pulumi.StringOutput {
	return o.ApplyT(func(v GetTrafficForwardingGREInternalIPRangeList) string { return v.EndIpAddress }).(pulumi.StringOutput)
}

func (o GetTrafficForwardingGREInternalIPRangeListOutput) StartIpAddress() pulumi.StringOutput {
	return o.ApplyT(func(v GetTrafficForwardingGREInternalIPRangeList) string { return v.StartIpAddress }).(pulumi.StringOutput)
}

type GetTrafficForwardingGREInternalIPRangeListArrayOutput struct{ *pulumi.OutputState }

func (GetTrafficForwardingGREInternalIPRangeListArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetTrafficForwardingGREInternalIPRangeList)(nil)).Elem()
}

func (o GetTrafficForwardingGREInternalIPRangeListArrayOutput) ToGetTrafficForwardingGREInternalIPRangeListArrayOutput() GetTrafficForwardingGREInternalIPRangeListArrayOutput {
	return o
}

func (o GetTrafficForwardingGREInternalIPRangeListArrayOutput) ToGetTrafficForwardingGREInternalIPRangeListArrayOutputWithContext(ctx context.Context) GetTrafficForwardingGREInternalIPRangeListArrayOutput {
	return o
}

func (o GetTrafficForwardingGREInternalIPRangeListArrayOutput) Index(i pulumi.IntInput) GetTrafficForwardingGREInternalIPRangeListOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetTrafficForwardingGREInternalIPRangeList {
		return vs[0].([]GetTrafficForwardingGREInternalIPRangeList)[vs[1].(int)]
	}).(GetTrafficForwardingGREInternalIPRangeListOutput)
}

type GetTrafficForwardingGRETunnelLastModifiedBy struct {
	Id   int    `pulumi:"id"`
	Name string `pulumi:"name"`
}

// GetTrafficForwardingGRETunnelLastModifiedByInput is an input type that accepts GetTrafficForwardingGRETunnelLastModifiedByArgs and GetTrafficForwardingGRETunnelLastModifiedByOutput values.
// You can construct a concrete instance of `GetTrafficForwardingGRETunnelLastModifiedByInput` via:
//
//	GetTrafficForwardingGRETunnelLastModifiedByArgs{...}
type GetTrafficForwardingGRETunnelLastModifiedByInput interface {
	pulumi.Input

	ToGetTrafficForwardingGRETunnelLastModifiedByOutput() GetTrafficForwardingGRETunnelLastModifiedByOutput
	ToGetTrafficForwardingGRETunnelLastModifiedByOutputWithContext(context.Context) GetTrafficForwardingGRETunnelLastModifiedByOutput
}

type GetTrafficForwardingGRETunnelLastModifiedByArgs struct {
	Id   pulumi.IntInput    `pulumi:"id"`
	Name pulumi.StringInput `pulumi:"name"`
}

func (GetTrafficForwardingGRETunnelLastModifiedByArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetTrafficForwardingGRETunnelLastModifiedBy)(nil)).Elem()
}

func (i GetTrafficForwardingGRETunnelLastModifiedByArgs) ToGetTrafficForwardingGRETunnelLastModifiedByOutput() GetTrafficForwardingGRETunnelLastModifiedByOutput {
	return i.ToGetTrafficForwardingGRETunnelLastModifiedByOutputWithContext(context.Background())
}

func (i GetTrafficForwardingGRETunnelLastModifiedByArgs) ToGetTrafficForwardingGRETunnelLastModifiedByOutputWithContext(ctx context.Context) GetTrafficForwardingGRETunnelLastModifiedByOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetTrafficForwardingGRETunnelLastModifiedByOutput)
}

// GetTrafficForwardingGRETunnelLastModifiedByArrayInput is an input type that accepts GetTrafficForwardingGRETunnelLastModifiedByArray and GetTrafficForwardingGRETunnelLastModifiedByArrayOutput values.
// You can construct a concrete instance of `GetTrafficForwardingGRETunnelLastModifiedByArrayInput` via:
//
//	GetTrafficForwardingGRETunnelLastModifiedByArray{ GetTrafficForwardingGRETunnelLastModifiedByArgs{...} }
type GetTrafficForwardingGRETunnelLastModifiedByArrayInput interface {
	pulumi.Input

	ToGetTrafficForwardingGRETunnelLastModifiedByArrayOutput() GetTrafficForwardingGRETunnelLastModifiedByArrayOutput
	ToGetTrafficForwardingGRETunnelLastModifiedByArrayOutputWithContext(context.Context) GetTrafficForwardingGRETunnelLastModifiedByArrayOutput
}

type GetTrafficForwardingGRETunnelLastModifiedByArray []GetTrafficForwardingGRETunnelLastModifiedByInput

func (GetTrafficForwardingGRETunnelLastModifiedByArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetTrafficForwardingGRETunnelLastModifiedBy)(nil)).Elem()
}

func (i GetTrafficForwardingGRETunnelLastModifiedByArray) ToGetTrafficForwardingGRETunnelLastModifiedByArrayOutput() GetTrafficForwardingGRETunnelLastModifiedByArrayOutput {
	return i.ToGetTrafficForwardingGRETunnelLastModifiedByArrayOutputWithContext(context.Background())
}

func (i GetTrafficForwardingGRETunnelLastModifiedByArray) ToGetTrafficForwardingGRETunnelLastModifiedByArrayOutputWithContext(ctx context.Context) GetTrafficForwardingGRETunnelLastModifiedByArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetTrafficForwardingGRETunnelLastModifiedByArrayOutput)
}

type GetTrafficForwardingGRETunnelLastModifiedByOutput struct{ *pulumi.OutputState }

func (GetTrafficForwardingGRETunnelLastModifiedByOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetTrafficForwardingGRETunnelLastModifiedBy)(nil)).Elem()
}

func (o GetTrafficForwardingGRETunnelLastModifiedByOutput) ToGetTrafficForwardingGRETunnelLastModifiedByOutput() GetTrafficForwardingGRETunnelLastModifiedByOutput {
	return o
}

func (o GetTrafficForwardingGRETunnelLastModifiedByOutput) ToGetTrafficForwardingGRETunnelLastModifiedByOutputWithContext(ctx context.Context) GetTrafficForwardingGRETunnelLastModifiedByOutput {
	return o
}

func (o GetTrafficForwardingGRETunnelLastModifiedByOutput) Id() pulumi.IntOutput {
	return o.ApplyT(func(v GetTrafficForwardingGRETunnelLastModifiedBy) int { return v.Id }).(pulumi.IntOutput)
}

func (o GetTrafficForwardingGRETunnelLastModifiedByOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetTrafficForwardingGRETunnelLastModifiedBy) string { return v.Name }).(pulumi.StringOutput)
}

type GetTrafficForwardingGRETunnelLastModifiedByArrayOutput struct{ *pulumi.OutputState }

func (GetTrafficForwardingGRETunnelLastModifiedByArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetTrafficForwardingGRETunnelLastModifiedBy)(nil)).Elem()
}

func (o GetTrafficForwardingGRETunnelLastModifiedByArrayOutput) ToGetTrafficForwardingGRETunnelLastModifiedByArrayOutput() GetTrafficForwardingGRETunnelLastModifiedByArrayOutput {
	return o
}

func (o GetTrafficForwardingGRETunnelLastModifiedByArrayOutput) ToGetTrafficForwardingGRETunnelLastModifiedByArrayOutputWithContext(ctx context.Context) GetTrafficForwardingGRETunnelLastModifiedByArrayOutput {
	return o
}

func (o GetTrafficForwardingGRETunnelLastModifiedByArrayOutput) Index(i pulumi.IntInput) GetTrafficForwardingGRETunnelLastModifiedByOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetTrafficForwardingGRETunnelLastModifiedBy {
		return vs[0].([]GetTrafficForwardingGRETunnelLastModifiedBy)[vs[1].(int)]
	}).(GetTrafficForwardingGRETunnelLastModifiedByOutput)
}

type GetTrafficForwardingGRETunnelManagedBy struct {
	Id   int    `pulumi:"id"`
	Name string `pulumi:"name"`
}

// GetTrafficForwardingGRETunnelManagedByInput is an input type that accepts GetTrafficForwardingGRETunnelManagedByArgs and GetTrafficForwardingGRETunnelManagedByOutput values.
// You can construct a concrete instance of `GetTrafficForwardingGRETunnelManagedByInput` via:
//
//	GetTrafficForwardingGRETunnelManagedByArgs{...}
type GetTrafficForwardingGRETunnelManagedByInput interface {
	pulumi.Input

	ToGetTrafficForwardingGRETunnelManagedByOutput() GetTrafficForwardingGRETunnelManagedByOutput
	ToGetTrafficForwardingGRETunnelManagedByOutputWithContext(context.Context) GetTrafficForwardingGRETunnelManagedByOutput
}

type GetTrafficForwardingGRETunnelManagedByArgs struct {
	Id   pulumi.IntInput    `pulumi:"id"`
	Name pulumi.StringInput `pulumi:"name"`
}

func (GetTrafficForwardingGRETunnelManagedByArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetTrafficForwardingGRETunnelManagedBy)(nil)).Elem()
}

func (i GetTrafficForwardingGRETunnelManagedByArgs) ToGetTrafficForwardingGRETunnelManagedByOutput() GetTrafficForwardingGRETunnelManagedByOutput {
	return i.ToGetTrafficForwardingGRETunnelManagedByOutputWithContext(context.Background())
}

func (i GetTrafficForwardingGRETunnelManagedByArgs) ToGetTrafficForwardingGRETunnelManagedByOutputWithContext(ctx context.Context) GetTrafficForwardingGRETunnelManagedByOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetTrafficForwardingGRETunnelManagedByOutput)
}

// GetTrafficForwardingGRETunnelManagedByArrayInput is an input type that accepts GetTrafficForwardingGRETunnelManagedByArray and GetTrafficForwardingGRETunnelManagedByArrayOutput values.
// You can construct a concrete instance of `GetTrafficForwardingGRETunnelManagedByArrayInput` via:
//
//	GetTrafficForwardingGRETunnelManagedByArray{ GetTrafficForwardingGRETunnelManagedByArgs{...} }
type GetTrafficForwardingGRETunnelManagedByArrayInput interface {
	pulumi.Input

	ToGetTrafficForwardingGRETunnelManagedByArrayOutput() GetTrafficForwardingGRETunnelManagedByArrayOutput
	ToGetTrafficForwardingGRETunnelManagedByArrayOutputWithContext(context.Context) GetTrafficForwardingGRETunnelManagedByArrayOutput
}

type GetTrafficForwardingGRETunnelManagedByArray []GetTrafficForwardingGRETunnelManagedByInput

func (GetTrafficForwardingGRETunnelManagedByArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetTrafficForwardingGRETunnelManagedBy)(nil)).Elem()
}

func (i GetTrafficForwardingGRETunnelManagedByArray) ToGetTrafficForwardingGRETunnelManagedByArrayOutput() GetTrafficForwardingGRETunnelManagedByArrayOutput {
	return i.ToGetTrafficForwardingGRETunnelManagedByArrayOutputWithContext(context.Background())
}

func (i GetTrafficForwardingGRETunnelManagedByArray) ToGetTrafficForwardingGRETunnelManagedByArrayOutputWithContext(ctx context.Context) GetTrafficForwardingGRETunnelManagedByArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetTrafficForwardingGRETunnelManagedByArrayOutput)
}

type GetTrafficForwardingGRETunnelManagedByOutput struct{ *pulumi.OutputState }

func (GetTrafficForwardingGRETunnelManagedByOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetTrafficForwardingGRETunnelManagedBy)(nil)).Elem()
}

func (o GetTrafficForwardingGRETunnelManagedByOutput) ToGetTrafficForwardingGRETunnelManagedByOutput() GetTrafficForwardingGRETunnelManagedByOutput {
	return o
}

func (o GetTrafficForwardingGRETunnelManagedByOutput) ToGetTrafficForwardingGRETunnelManagedByOutputWithContext(ctx context.Context) GetTrafficForwardingGRETunnelManagedByOutput {
	return o
}

func (o GetTrafficForwardingGRETunnelManagedByOutput) Id() pulumi.IntOutput {
	return o.ApplyT(func(v GetTrafficForwardingGRETunnelManagedBy) int { return v.Id }).(pulumi.IntOutput)
}

func (o GetTrafficForwardingGRETunnelManagedByOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetTrafficForwardingGRETunnelManagedBy) string { return v.Name }).(pulumi.StringOutput)
}

type GetTrafficForwardingGRETunnelManagedByArrayOutput struct{ *pulumi.OutputState }

func (GetTrafficForwardingGRETunnelManagedByArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetTrafficForwardingGRETunnelManagedBy)(nil)).Elem()
}

func (o GetTrafficForwardingGRETunnelManagedByArrayOutput) ToGetTrafficForwardingGRETunnelManagedByArrayOutput() GetTrafficForwardingGRETunnelManagedByArrayOutput {
	return o
}

func (o GetTrafficForwardingGRETunnelManagedByArrayOutput) ToGetTrafficForwardingGRETunnelManagedByArrayOutputWithContext(ctx context.Context) GetTrafficForwardingGRETunnelManagedByArrayOutput {
	return o
}

func (o GetTrafficForwardingGRETunnelManagedByArrayOutput) Index(i pulumi.IntInput) GetTrafficForwardingGRETunnelManagedByOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetTrafficForwardingGRETunnelManagedBy {
		return vs[0].([]GetTrafficForwardingGRETunnelManagedBy)[vs[1].(int)]
	}).(GetTrafficForwardingGRETunnelManagedByOutput)
}

type GetTrafficForwardingGRETunnelPrimaryDestVip struct {
	City               string `pulumi:"city"`
	CountryCode        string `pulumi:"countryCode"`
	Datacenter         string `pulumi:"datacenter"`
	Id                 int    `pulumi:"id"`
	Latitude           int    `pulumi:"latitude"`
	Longitude          int    `pulumi:"longitude"`
	PrivateServiceEdge bool   `pulumi:"privateServiceEdge"`
	Region             string `pulumi:"region"`
	VirtualIp          string `pulumi:"virtualIp"`
}

// GetTrafficForwardingGRETunnelPrimaryDestVipInput is an input type that accepts GetTrafficForwardingGRETunnelPrimaryDestVipArgs and GetTrafficForwardingGRETunnelPrimaryDestVipOutput values.
// You can construct a concrete instance of `GetTrafficForwardingGRETunnelPrimaryDestVipInput` via:
//
//	GetTrafficForwardingGRETunnelPrimaryDestVipArgs{...}
type GetTrafficForwardingGRETunnelPrimaryDestVipInput interface {
	pulumi.Input

	ToGetTrafficForwardingGRETunnelPrimaryDestVipOutput() GetTrafficForwardingGRETunnelPrimaryDestVipOutput
	ToGetTrafficForwardingGRETunnelPrimaryDestVipOutputWithContext(context.Context) GetTrafficForwardingGRETunnelPrimaryDestVipOutput
}

type GetTrafficForwardingGRETunnelPrimaryDestVipArgs struct {
	City               pulumi.StringInput `pulumi:"city"`
	CountryCode        pulumi.StringInput `pulumi:"countryCode"`
	Datacenter         pulumi.StringInput `pulumi:"datacenter"`
	Id                 pulumi.IntInput    `pulumi:"id"`
	Latitude           pulumi.IntInput    `pulumi:"latitude"`
	Longitude          pulumi.IntInput    `pulumi:"longitude"`
	PrivateServiceEdge pulumi.BoolInput   `pulumi:"privateServiceEdge"`
	Region             pulumi.StringInput `pulumi:"region"`
	VirtualIp          pulumi.StringInput `pulumi:"virtualIp"`
}

func (GetTrafficForwardingGRETunnelPrimaryDestVipArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetTrafficForwardingGRETunnelPrimaryDestVip)(nil)).Elem()
}

func (i GetTrafficForwardingGRETunnelPrimaryDestVipArgs) ToGetTrafficForwardingGRETunnelPrimaryDestVipOutput() GetTrafficForwardingGRETunnelPrimaryDestVipOutput {
	return i.ToGetTrafficForwardingGRETunnelPrimaryDestVipOutputWithContext(context.Background())
}

func (i GetTrafficForwardingGRETunnelPrimaryDestVipArgs) ToGetTrafficForwardingGRETunnelPrimaryDestVipOutputWithContext(ctx context.Context) GetTrafficForwardingGRETunnelPrimaryDestVipOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetTrafficForwardingGRETunnelPrimaryDestVipOutput)
}

// GetTrafficForwardingGRETunnelPrimaryDestVipArrayInput is an input type that accepts GetTrafficForwardingGRETunnelPrimaryDestVipArray and GetTrafficForwardingGRETunnelPrimaryDestVipArrayOutput values.
// You can construct a concrete instance of `GetTrafficForwardingGRETunnelPrimaryDestVipArrayInput` via:
//
//	GetTrafficForwardingGRETunnelPrimaryDestVipArray{ GetTrafficForwardingGRETunnelPrimaryDestVipArgs{...} }
type GetTrafficForwardingGRETunnelPrimaryDestVipArrayInput interface {
	pulumi.Input

	ToGetTrafficForwardingGRETunnelPrimaryDestVipArrayOutput() GetTrafficForwardingGRETunnelPrimaryDestVipArrayOutput
	ToGetTrafficForwardingGRETunnelPrimaryDestVipArrayOutputWithContext(context.Context) GetTrafficForwardingGRETunnelPrimaryDestVipArrayOutput
}

type GetTrafficForwardingGRETunnelPrimaryDestVipArray []GetTrafficForwardingGRETunnelPrimaryDestVipInput

func (GetTrafficForwardingGRETunnelPrimaryDestVipArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetTrafficForwardingGRETunnelPrimaryDestVip)(nil)).Elem()
}

func (i GetTrafficForwardingGRETunnelPrimaryDestVipArray) ToGetTrafficForwardingGRETunnelPrimaryDestVipArrayOutput() GetTrafficForwardingGRETunnelPrimaryDestVipArrayOutput {
	return i.ToGetTrafficForwardingGRETunnelPrimaryDestVipArrayOutputWithContext(context.Background())
}

func (i GetTrafficForwardingGRETunnelPrimaryDestVipArray) ToGetTrafficForwardingGRETunnelPrimaryDestVipArrayOutputWithContext(ctx context.Context) GetTrafficForwardingGRETunnelPrimaryDestVipArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetTrafficForwardingGRETunnelPrimaryDestVipArrayOutput)
}

type GetTrafficForwardingGRETunnelPrimaryDestVipOutput struct{ *pulumi.OutputState }

func (GetTrafficForwardingGRETunnelPrimaryDestVipOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetTrafficForwardingGRETunnelPrimaryDestVip)(nil)).Elem()
}

func (o GetTrafficForwardingGRETunnelPrimaryDestVipOutput) ToGetTrafficForwardingGRETunnelPrimaryDestVipOutput() GetTrafficForwardingGRETunnelPrimaryDestVipOutput {
	return o
}

func (o GetTrafficForwardingGRETunnelPrimaryDestVipOutput) ToGetTrafficForwardingGRETunnelPrimaryDestVipOutputWithContext(ctx context.Context) GetTrafficForwardingGRETunnelPrimaryDestVipOutput {
	return o
}

func (o GetTrafficForwardingGRETunnelPrimaryDestVipOutput) City() pulumi.StringOutput {
	return o.ApplyT(func(v GetTrafficForwardingGRETunnelPrimaryDestVip) string { return v.City }).(pulumi.StringOutput)
}

func (o GetTrafficForwardingGRETunnelPrimaryDestVipOutput) CountryCode() pulumi.StringOutput {
	return o.ApplyT(func(v GetTrafficForwardingGRETunnelPrimaryDestVip) string { return v.CountryCode }).(pulumi.StringOutput)
}

func (o GetTrafficForwardingGRETunnelPrimaryDestVipOutput) Datacenter() pulumi.StringOutput {
	return o.ApplyT(func(v GetTrafficForwardingGRETunnelPrimaryDestVip) string { return v.Datacenter }).(pulumi.StringOutput)
}

func (o GetTrafficForwardingGRETunnelPrimaryDestVipOutput) Id() pulumi.IntOutput {
	return o.ApplyT(func(v GetTrafficForwardingGRETunnelPrimaryDestVip) int { return v.Id }).(pulumi.IntOutput)
}

func (o GetTrafficForwardingGRETunnelPrimaryDestVipOutput) Latitude() pulumi.IntOutput {
	return o.ApplyT(func(v GetTrafficForwardingGRETunnelPrimaryDestVip) int { return v.Latitude }).(pulumi.IntOutput)
}

func (o GetTrafficForwardingGRETunnelPrimaryDestVipOutput) Longitude() pulumi.IntOutput {
	return o.ApplyT(func(v GetTrafficForwardingGRETunnelPrimaryDestVip) int { return v.Longitude }).(pulumi.IntOutput)
}

func (o GetTrafficForwardingGRETunnelPrimaryDestVipOutput) PrivateServiceEdge() pulumi.BoolOutput {
	return o.ApplyT(func(v GetTrafficForwardingGRETunnelPrimaryDestVip) bool { return v.PrivateServiceEdge }).(pulumi.BoolOutput)
}

func (o GetTrafficForwardingGRETunnelPrimaryDestVipOutput) Region() pulumi.StringOutput {
	return o.ApplyT(func(v GetTrafficForwardingGRETunnelPrimaryDestVip) string { return v.Region }).(pulumi.StringOutput)
}

func (o GetTrafficForwardingGRETunnelPrimaryDestVipOutput) VirtualIp() pulumi.StringOutput {
	return o.ApplyT(func(v GetTrafficForwardingGRETunnelPrimaryDestVip) string { return v.VirtualIp }).(pulumi.StringOutput)
}

type GetTrafficForwardingGRETunnelPrimaryDestVipArrayOutput struct{ *pulumi.OutputState }

func (GetTrafficForwardingGRETunnelPrimaryDestVipArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetTrafficForwardingGRETunnelPrimaryDestVip)(nil)).Elem()
}

func (o GetTrafficForwardingGRETunnelPrimaryDestVipArrayOutput) ToGetTrafficForwardingGRETunnelPrimaryDestVipArrayOutput() GetTrafficForwardingGRETunnelPrimaryDestVipArrayOutput {
	return o
}

func (o GetTrafficForwardingGRETunnelPrimaryDestVipArrayOutput) ToGetTrafficForwardingGRETunnelPrimaryDestVipArrayOutputWithContext(ctx context.Context) GetTrafficForwardingGRETunnelPrimaryDestVipArrayOutput {
	return o
}

func (o GetTrafficForwardingGRETunnelPrimaryDestVipArrayOutput) Index(i pulumi.IntInput) GetTrafficForwardingGRETunnelPrimaryDestVipOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetTrafficForwardingGRETunnelPrimaryDestVip {
		return vs[0].([]GetTrafficForwardingGRETunnelPrimaryDestVip)[vs[1].(int)]
	}).(GetTrafficForwardingGRETunnelPrimaryDestVipOutput)
}

type GetTrafficForwardingGRETunnelSecondaryDestVip struct {
	City               string `pulumi:"city"`
	CountryCode        string `pulumi:"countryCode"`
	Datacenter         string `pulumi:"datacenter"`
	Id                 int    `pulumi:"id"`
	Latitude           int    `pulumi:"latitude"`
	Longitude          int    `pulumi:"longitude"`
	PrivateServiceEdge bool   `pulumi:"privateServiceEdge"`
	Region             string `pulumi:"region"`
	VirtualIp          string `pulumi:"virtualIp"`
}

// GetTrafficForwardingGRETunnelSecondaryDestVipInput is an input type that accepts GetTrafficForwardingGRETunnelSecondaryDestVipArgs and GetTrafficForwardingGRETunnelSecondaryDestVipOutput values.
// You can construct a concrete instance of `GetTrafficForwardingGRETunnelSecondaryDestVipInput` via:
//
//	GetTrafficForwardingGRETunnelSecondaryDestVipArgs{...}
type GetTrafficForwardingGRETunnelSecondaryDestVipInput interface {
	pulumi.Input

	ToGetTrafficForwardingGRETunnelSecondaryDestVipOutput() GetTrafficForwardingGRETunnelSecondaryDestVipOutput
	ToGetTrafficForwardingGRETunnelSecondaryDestVipOutputWithContext(context.Context) GetTrafficForwardingGRETunnelSecondaryDestVipOutput
}

type GetTrafficForwardingGRETunnelSecondaryDestVipArgs struct {
	City               pulumi.StringInput `pulumi:"city"`
	CountryCode        pulumi.StringInput `pulumi:"countryCode"`
	Datacenter         pulumi.StringInput `pulumi:"datacenter"`
	Id                 pulumi.IntInput    `pulumi:"id"`
	Latitude           pulumi.IntInput    `pulumi:"latitude"`
	Longitude          pulumi.IntInput    `pulumi:"longitude"`
	PrivateServiceEdge pulumi.BoolInput   `pulumi:"privateServiceEdge"`
	Region             pulumi.StringInput `pulumi:"region"`
	VirtualIp          pulumi.StringInput `pulumi:"virtualIp"`
}

func (GetTrafficForwardingGRETunnelSecondaryDestVipArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetTrafficForwardingGRETunnelSecondaryDestVip)(nil)).Elem()
}

func (i GetTrafficForwardingGRETunnelSecondaryDestVipArgs) ToGetTrafficForwardingGRETunnelSecondaryDestVipOutput() GetTrafficForwardingGRETunnelSecondaryDestVipOutput {
	return i.ToGetTrafficForwardingGRETunnelSecondaryDestVipOutputWithContext(context.Background())
}

func (i GetTrafficForwardingGRETunnelSecondaryDestVipArgs) ToGetTrafficForwardingGRETunnelSecondaryDestVipOutputWithContext(ctx context.Context) GetTrafficForwardingGRETunnelSecondaryDestVipOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetTrafficForwardingGRETunnelSecondaryDestVipOutput)
}

// GetTrafficForwardingGRETunnelSecondaryDestVipArrayInput is an input type that accepts GetTrafficForwardingGRETunnelSecondaryDestVipArray and GetTrafficForwardingGRETunnelSecondaryDestVipArrayOutput values.
// You can construct a concrete instance of `GetTrafficForwardingGRETunnelSecondaryDestVipArrayInput` via:
//
//	GetTrafficForwardingGRETunnelSecondaryDestVipArray{ GetTrafficForwardingGRETunnelSecondaryDestVipArgs{...} }
type GetTrafficForwardingGRETunnelSecondaryDestVipArrayInput interface {
	pulumi.Input

	ToGetTrafficForwardingGRETunnelSecondaryDestVipArrayOutput() GetTrafficForwardingGRETunnelSecondaryDestVipArrayOutput
	ToGetTrafficForwardingGRETunnelSecondaryDestVipArrayOutputWithContext(context.Context) GetTrafficForwardingGRETunnelSecondaryDestVipArrayOutput
}

type GetTrafficForwardingGRETunnelSecondaryDestVipArray []GetTrafficForwardingGRETunnelSecondaryDestVipInput

func (GetTrafficForwardingGRETunnelSecondaryDestVipArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetTrafficForwardingGRETunnelSecondaryDestVip)(nil)).Elem()
}

func (i GetTrafficForwardingGRETunnelSecondaryDestVipArray) ToGetTrafficForwardingGRETunnelSecondaryDestVipArrayOutput() GetTrafficForwardingGRETunnelSecondaryDestVipArrayOutput {
	return i.ToGetTrafficForwardingGRETunnelSecondaryDestVipArrayOutputWithContext(context.Background())
}

func (i GetTrafficForwardingGRETunnelSecondaryDestVipArray) ToGetTrafficForwardingGRETunnelSecondaryDestVipArrayOutputWithContext(ctx context.Context) GetTrafficForwardingGRETunnelSecondaryDestVipArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetTrafficForwardingGRETunnelSecondaryDestVipArrayOutput)
}

type GetTrafficForwardingGRETunnelSecondaryDestVipOutput struct{ *pulumi.OutputState }

func (GetTrafficForwardingGRETunnelSecondaryDestVipOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetTrafficForwardingGRETunnelSecondaryDestVip)(nil)).Elem()
}

func (o GetTrafficForwardingGRETunnelSecondaryDestVipOutput) ToGetTrafficForwardingGRETunnelSecondaryDestVipOutput() GetTrafficForwardingGRETunnelSecondaryDestVipOutput {
	return o
}

func (o GetTrafficForwardingGRETunnelSecondaryDestVipOutput) ToGetTrafficForwardingGRETunnelSecondaryDestVipOutputWithContext(ctx context.Context) GetTrafficForwardingGRETunnelSecondaryDestVipOutput {
	return o
}

func (o GetTrafficForwardingGRETunnelSecondaryDestVipOutput) City() pulumi.StringOutput {
	return o.ApplyT(func(v GetTrafficForwardingGRETunnelSecondaryDestVip) string { return v.City }).(pulumi.StringOutput)
}

func (o GetTrafficForwardingGRETunnelSecondaryDestVipOutput) CountryCode() pulumi.StringOutput {
	return o.ApplyT(func(v GetTrafficForwardingGRETunnelSecondaryDestVip) string { return v.CountryCode }).(pulumi.StringOutput)
}

func (o GetTrafficForwardingGRETunnelSecondaryDestVipOutput) Datacenter() pulumi.StringOutput {
	return o.ApplyT(func(v GetTrafficForwardingGRETunnelSecondaryDestVip) string { return v.Datacenter }).(pulumi.StringOutput)
}

func (o GetTrafficForwardingGRETunnelSecondaryDestVipOutput) Id() pulumi.IntOutput {
	return o.ApplyT(func(v GetTrafficForwardingGRETunnelSecondaryDestVip) int { return v.Id }).(pulumi.IntOutput)
}

func (o GetTrafficForwardingGRETunnelSecondaryDestVipOutput) Latitude() pulumi.IntOutput {
	return o.ApplyT(func(v GetTrafficForwardingGRETunnelSecondaryDestVip) int { return v.Latitude }).(pulumi.IntOutput)
}

func (o GetTrafficForwardingGRETunnelSecondaryDestVipOutput) Longitude() pulumi.IntOutput {
	return o.ApplyT(func(v GetTrafficForwardingGRETunnelSecondaryDestVip) int { return v.Longitude }).(pulumi.IntOutput)
}

func (o GetTrafficForwardingGRETunnelSecondaryDestVipOutput) PrivateServiceEdge() pulumi.BoolOutput {
	return o.ApplyT(func(v GetTrafficForwardingGRETunnelSecondaryDestVip) bool { return v.PrivateServiceEdge }).(pulumi.BoolOutput)
}

func (o GetTrafficForwardingGRETunnelSecondaryDestVipOutput) Region() pulumi.StringOutput {
	return o.ApplyT(func(v GetTrafficForwardingGRETunnelSecondaryDestVip) string { return v.Region }).(pulumi.StringOutput)
}

func (o GetTrafficForwardingGRETunnelSecondaryDestVipOutput) VirtualIp() pulumi.StringOutput {
	return o.ApplyT(func(v GetTrafficForwardingGRETunnelSecondaryDestVip) string { return v.VirtualIp }).(pulumi.StringOutput)
}

type GetTrafficForwardingGRETunnelSecondaryDestVipArrayOutput struct{ *pulumi.OutputState }

func (GetTrafficForwardingGRETunnelSecondaryDestVipArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetTrafficForwardingGRETunnelSecondaryDestVip)(nil)).Elem()
}

func (o GetTrafficForwardingGRETunnelSecondaryDestVipArrayOutput) ToGetTrafficForwardingGRETunnelSecondaryDestVipArrayOutput() GetTrafficForwardingGRETunnelSecondaryDestVipArrayOutput {
	return o
}

func (o GetTrafficForwardingGRETunnelSecondaryDestVipArrayOutput) ToGetTrafficForwardingGRETunnelSecondaryDestVipArrayOutputWithContext(ctx context.Context) GetTrafficForwardingGRETunnelSecondaryDestVipArrayOutput {
	return o
}

func (o GetTrafficForwardingGRETunnelSecondaryDestVipArrayOutput) Index(i pulumi.IntInput) GetTrafficForwardingGRETunnelSecondaryDestVipOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetTrafficForwardingGRETunnelSecondaryDestVip {
		return vs[0].([]GetTrafficForwardingGRETunnelSecondaryDestVip)[vs[1].(int)]
	}).(GetTrafficForwardingGRETunnelSecondaryDestVipOutput)
}

type GetTrafficForwardingStaticIPLastModifiedBy struct {
	// (Map of String)
	Extensions map[string]string `pulumi:"extensions"`
	// The unique identifier for the static IP address
	Id int `pulumi:"id"`
	// (String) The configured name of the entity
	Name string `pulumi:"name"`
}

// GetTrafficForwardingStaticIPLastModifiedByInput is an input type that accepts GetTrafficForwardingStaticIPLastModifiedByArgs and GetTrafficForwardingStaticIPLastModifiedByOutput values.
// You can construct a concrete instance of `GetTrafficForwardingStaticIPLastModifiedByInput` via:
//
//	GetTrafficForwardingStaticIPLastModifiedByArgs{...}
type GetTrafficForwardingStaticIPLastModifiedByInput interface {
	pulumi.Input

	ToGetTrafficForwardingStaticIPLastModifiedByOutput() GetTrafficForwardingStaticIPLastModifiedByOutput
	ToGetTrafficForwardingStaticIPLastModifiedByOutputWithContext(context.Context) GetTrafficForwardingStaticIPLastModifiedByOutput
}

type GetTrafficForwardingStaticIPLastModifiedByArgs struct {
	// (Map of String)
	Extensions pulumi.StringMapInput `pulumi:"extensions"`
	// The unique identifier for the static IP address
	Id pulumi.IntInput `pulumi:"id"`
	// (String) The configured name of the entity
	Name pulumi.StringInput `pulumi:"name"`
}

func (GetTrafficForwardingStaticIPLastModifiedByArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetTrafficForwardingStaticIPLastModifiedBy)(nil)).Elem()
}

func (i GetTrafficForwardingStaticIPLastModifiedByArgs) ToGetTrafficForwardingStaticIPLastModifiedByOutput() GetTrafficForwardingStaticIPLastModifiedByOutput {
	return i.ToGetTrafficForwardingStaticIPLastModifiedByOutputWithContext(context.Background())
}

func (i GetTrafficForwardingStaticIPLastModifiedByArgs) ToGetTrafficForwardingStaticIPLastModifiedByOutputWithContext(ctx context.Context) GetTrafficForwardingStaticIPLastModifiedByOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetTrafficForwardingStaticIPLastModifiedByOutput)
}

// GetTrafficForwardingStaticIPLastModifiedByArrayInput is an input type that accepts GetTrafficForwardingStaticIPLastModifiedByArray and GetTrafficForwardingStaticIPLastModifiedByArrayOutput values.
// You can construct a concrete instance of `GetTrafficForwardingStaticIPLastModifiedByArrayInput` via:
//
//	GetTrafficForwardingStaticIPLastModifiedByArray{ GetTrafficForwardingStaticIPLastModifiedByArgs{...} }
type GetTrafficForwardingStaticIPLastModifiedByArrayInput interface {
	pulumi.Input

	ToGetTrafficForwardingStaticIPLastModifiedByArrayOutput() GetTrafficForwardingStaticIPLastModifiedByArrayOutput
	ToGetTrafficForwardingStaticIPLastModifiedByArrayOutputWithContext(context.Context) GetTrafficForwardingStaticIPLastModifiedByArrayOutput
}

type GetTrafficForwardingStaticIPLastModifiedByArray []GetTrafficForwardingStaticIPLastModifiedByInput

func (GetTrafficForwardingStaticIPLastModifiedByArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetTrafficForwardingStaticIPLastModifiedBy)(nil)).Elem()
}

func (i GetTrafficForwardingStaticIPLastModifiedByArray) ToGetTrafficForwardingStaticIPLastModifiedByArrayOutput() GetTrafficForwardingStaticIPLastModifiedByArrayOutput {
	return i.ToGetTrafficForwardingStaticIPLastModifiedByArrayOutputWithContext(context.Background())
}

func (i GetTrafficForwardingStaticIPLastModifiedByArray) ToGetTrafficForwardingStaticIPLastModifiedByArrayOutputWithContext(ctx context.Context) GetTrafficForwardingStaticIPLastModifiedByArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetTrafficForwardingStaticIPLastModifiedByArrayOutput)
}

type GetTrafficForwardingStaticIPLastModifiedByOutput struct{ *pulumi.OutputState }

func (GetTrafficForwardingStaticIPLastModifiedByOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetTrafficForwardingStaticIPLastModifiedBy)(nil)).Elem()
}

func (o GetTrafficForwardingStaticIPLastModifiedByOutput) ToGetTrafficForwardingStaticIPLastModifiedByOutput() GetTrafficForwardingStaticIPLastModifiedByOutput {
	return o
}

func (o GetTrafficForwardingStaticIPLastModifiedByOutput) ToGetTrafficForwardingStaticIPLastModifiedByOutputWithContext(ctx context.Context) GetTrafficForwardingStaticIPLastModifiedByOutput {
	return o
}

// (Map of String)
func (o GetTrafficForwardingStaticIPLastModifiedByOutput) Extensions() pulumi.StringMapOutput {
	return o.ApplyT(func(v GetTrafficForwardingStaticIPLastModifiedBy) map[string]string { return v.Extensions }).(pulumi.StringMapOutput)
}

// The unique identifier for the static IP address
func (o GetTrafficForwardingStaticIPLastModifiedByOutput) Id() pulumi.IntOutput {
	return o.ApplyT(func(v GetTrafficForwardingStaticIPLastModifiedBy) int { return v.Id }).(pulumi.IntOutput)
}

// (String) The configured name of the entity
func (o GetTrafficForwardingStaticIPLastModifiedByOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetTrafficForwardingStaticIPLastModifiedBy) string { return v.Name }).(pulumi.StringOutput)
}

type GetTrafficForwardingStaticIPLastModifiedByArrayOutput struct{ *pulumi.OutputState }

func (GetTrafficForwardingStaticIPLastModifiedByArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetTrafficForwardingStaticIPLastModifiedBy)(nil)).Elem()
}

func (o GetTrafficForwardingStaticIPLastModifiedByArrayOutput) ToGetTrafficForwardingStaticIPLastModifiedByArrayOutput() GetTrafficForwardingStaticIPLastModifiedByArrayOutput {
	return o
}

func (o GetTrafficForwardingStaticIPLastModifiedByArrayOutput) ToGetTrafficForwardingStaticIPLastModifiedByArrayOutputWithContext(ctx context.Context) GetTrafficForwardingStaticIPLastModifiedByArrayOutput {
	return o
}

func (o GetTrafficForwardingStaticIPLastModifiedByArrayOutput) Index(i pulumi.IntInput) GetTrafficForwardingStaticIPLastModifiedByOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetTrafficForwardingStaticIPLastModifiedBy {
		return vs[0].([]GetTrafficForwardingStaticIPLastModifiedBy)[vs[1].(int)]
	}).(GetTrafficForwardingStaticIPLastModifiedByOutput)
}

type GetTrafficForwardingStaticIPManagedBy struct {
	// The unique identifier for the static IP address
	Id int `pulumi:"id"`
	// (String) The configured name of the entity
	Name string `pulumi:"name"`
}

// GetTrafficForwardingStaticIPManagedByInput is an input type that accepts GetTrafficForwardingStaticIPManagedByArgs and GetTrafficForwardingStaticIPManagedByOutput values.
// You can construct a concrete instance of `GetTrafficForwardingStaticIPManagedByInput` via:
//
//	GetTrafficForwardingStaticIPManagedByArgs{...}
type GetTrafficForwardingStaticIPManagedByInput interface {
	pulumi.Input

	ToGetTrafficForwardingStaticIPManagedByOutput() GetTrafficForwardingStaticIPManagedByOutput
	ToGetTrafficForwardingStaticIPManagedByOutputWithContext(context.Context) GetTrafficForwardingStaticIPManagedByOutput
}

type GetTrafficForwardingStaticIPManagedByArgs struct {
	// The unique identifier for the static IP address
	Id pulumi.IntInput `pulumi:"id"`
	// (String) The configured name of the entity
	Name pulumi.StringInput `pulumi:"name"`
}

func (GetTrafficForwardingStaticIPManagedByArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetTrafficForwardingStaticIPManagedBy)(nil)).Elem()
}

func (i GetTrafficForwardingStaticIPManagedByArgs) ToGetTrafficForwardingStaticIPManagedByOutput() GetTrafficForwardingStaticIPManagedByOutput {
	return i.ToGetTrafficForwardingStaticIPManagedByOutputWithContext(context.Background())
}

func (i GetTrafficForwardingStaticIPManagedByArgs) ToGetTrafficForwardingStaticIPManagedByOutputWithContext(ctx context.Context) GetTrafficForwardingStaticIPManagedByOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetTrafficForwardingStaticIPManagedByOutput)
}

// GetTrafficForwardingStaticIPManagedByArrayInput is an input type that accepts GetTrafficForwardingStaticIPManagedByArray and GetTrafficForwardingStaticIPManagedByArrayOutput values.
// You can construct a concrete instance of `GetTrafficForwardingStaticIPManagedByArrayInput` via:
//
//	GetTrafficForwardingStaticIPManagedByArray{ GetTrafficForwardingStaticIPManagedByArgs{...} }
type GetTrafficForwardingStaticIPManagedByArrayInput interface {
	pulumi.Input

	ToGetTrafficForwardingStaticIPManagedByArrayOutput() GetTrafficForwardingStaticIPManagedByArrayOutput
	ToGetTrafficForwardingStaticIPManagedByArrayOutputWithContext(context.Context) GetTrafficForwardingStaticIPManagedByArrayOutput
}

type GetTrafficForwardingStaticIPManagedByArray []GetTrafficForwardingStaticIPManagedByInput

func (GetTrafficForwardingStaticIPManagedByArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetTrafficForwardingStaticIPManagedBy)(nil)).Elem()
}

func (i GetTrafficForwardingStaticIPManagedByArray) ToGetTrafficForwardingStaticIPManagedByArrayOutput() GetTrafficForwardingStaticIPManagedByArrayOutput {
	return i.ToGetTrafficForwardingStaticIPManagedByArrayOutputWithContext(context.Background())
}

func (i GetTrafficForwardingStaticIPManagedByArray) ToGetTrafficForwardingStaticIPManagedByArrayOutputWithContext(ctx context.Context) GetTrafficForwardingStaticIPManagedByArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetTrafficForwardingStaticIPManagedByArrayOutput)
}

type GetTrafficForwardingStaticIPManagedByOutput struct{ *pulumi.OutputState }

func (GetTrafficForwardingStaticIPManagedByOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetTrafficForwardingStaticIPManagedBy)(nil)).Elem()
}

func (o GetTrafficForwardingStaticIPManagedByOutput) ToGetTrafficForwardingStaticIPManagedByOutput() GetTrafficForwardingStaticIPManagedByOutput {
	return o
}

func (o GetTrafficForwardingStaticIPManagedByOutput) ToGetTrafficForwardingStaticIPManagedByOutputWithContext(ctx context.Context) GetTrafficForwardingStaticIPManagedByOutput {
	return o
}

// The unique identifier for the static IP address
func (o GetTrafficForwardingStaticIPManagedByOutput) Id() pulumi.IntOutput {
	return o.ApplyT(func(v GetTrafficForwardingStaticIPManagedBy) int { return v.Id }).(pulumi.IntOutput)
}

// (String) The configured name of the entity
func (o GetTrafficForwardingStaticIPManagedByOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetTrafficForwardingStaticIPManagedBy) string { return v.Name }).(pulumi.StringOutput)
}

type GetTrafficForwardingStaticIPManagedByArrayOutput struct{ *pulumi.OutputState }

func (GetTrafficForwardingStaticIPManagedByArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetTrafficForwardingStaticIPManagedBy)(nil)).Elem()
}

func (o GetTrafficForwardingStaticIPManagedByArrayOutput) ToGetTrafficForwardingStaticIPManagedByArrayOutput() GetTrafficForwardingStaticIPManagedByArrayOutput {
	return o
}

func (o GetTrafficForwardingStaticIPManagedByArrayOutput) ToGetTrafficForwardingStaticIPManagedByArrayOutputWithContext(ctx context.Context) GetTrafficForwardingStaticIPManagedByArrayOutput {
	return o
}

func (o GetTrafficForwardingStaticIPManagedByArrayOutput) Index(i pulumi.IntInput) GetTrafficForwardingStaticIPManagedByOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetTrafficForwardingStaticIPManagedBy {
		return vs[0].([]GetTrafficForwardingStaticIPManagedBy)[vs[1].(int)]
	}).(GetTrafficForwardingStaticIPManagedByOutput)
}

type GetTrafficForwardingVIPRecommendedListList struct {
	// (String) Data center information
	Datacenter *string `pulumi:"datacenter"`
	// Unique identifer of the GRE virtual IP address (VIP)
	Id *int `pulumi:"id"`
	// (Boolean) Set to true if the virtual IP address (VIP) is a ZIA Private Service Edge
	PrivateServiceEdge *bool `pulumi:"privateServiceEdge"`
	// (String) GRE cluster virtual IP address (VIP)
	VirtualIp *string `pulumi:"virtualIp"`
}

// GetTrafficForwardingVIPRecommendedListListInput is an input type that accepts GetTrafficForwardingVIPRecommendedListListArgs and GetTrafficForwardingVIPRecommendedListListOutput values.
// You can construct a concrete instance of `GetTrafficForwardingVIPRecommendedListListInput` via:
//
//	GetTrafficForwardingVIPRecommendedListListArgs{...}
type GetTrafficForwardingVIPRecommendedListListInput interface {
	pulumi.Input

	ToGetTrafficForwardingVIPRecommendedListListOutput() GetTrafficForwardingVIPRecommendedListListOutput
	ToGetTrafficForwardingVIPRecommendedListListOutputWithContext(context.Context) GetTrafficForwardingVIPRecommendedListListOutput
}

type GetTrafficForwardingVIPRecommendedListListArgs struct {
	// (String) Data center information
	Datacenter pulumi.StringPtrInput `pulumi:"datacenter"`
	// Unique identifer of the GRE virtual IP address (VIP)
	Id pulumi.IntPtrInput `pulumi:"id"`
	// (Boolean) Set to true if the virtual IP address (VIP) is a ZIA Private Service Edge
	PrivateServiceEdge pulumi.BoolPtrInput `pulumi:"privateServiceEdge"`
	// (String) GRE cluster virtual IP address (VIP)
	VirtualIp pulumi.StringPtrInput `pulumi:"virtualIp"`
}

func (GetTrafficForwardingVIPRecommendedListListArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetTrafficForwardingVIPRecommendedListList)(nil)).Elem()
}

func (i GetTrafficForwardingVIPRecommendedListListArgs) ToGetTrafficForwardingVIPRecommendedListListOutput() GetTrafficForwardingVIPRecommendedListListOutput {
	return i.ToGetTrafficForwardingVIPRecommendedListListOutputWithContext(context.Background())
}

func (i GetTrafficForwardingVIPRecommendedListListArgs) ToGetTrafficForwardingVIPRecommendedListListOutputWithContext(ctx context.Context) GetTrafficForwardingVIPRecommendedListListOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetTrafficForwardingVIPRecommendedListListOutput)
}

// GetTrafficForwardingVIPRecommendedListListArrayInput is an input type that accepts GetTrafficForwardingVIPRecommendedListListArray and GetTrafficForwardingVIPRecommendedListListArrayOutput values.
// You can construct a concrete instance of `GetTrafficForwardingVIPRecommendedListListArrayInput` via:
//
//	GetTrafficForwardingVIPRecommendedListListArray{ GetTrafficForwardingVIPRecommendedListListArgs{...} }
type GetTrafficForwardingVIPRecommendedListListArrayInput interface {
	pulumi.Input

	ToGetTrafficForwardingVIPRecommendedListListArrayOutput() GetTrafficForwardingVIPRecommendedListListArrayOutput
	ToGetTrafficForwardingVIPRecommendedListListArrayOutputWithContext(context.Context) GetTrafficForwardingVIPRecommendedListListArrayOutput
}

type GetTrafficForwardingVIPRecommendedListListArray []GetTrafficForwardingVIPRecommendedListListInput

func (GetTrafficForwardingVIPRecommendedListListArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetTrafficForwardingVIPRecommendedListList)(nil)).Elem()
}

func (i GetTrafficForwardingVIPRecommendedListListArray) ToGetTrafficForwardingVIPRecommendedListListArrayOutput() GetTrafficForwardingVIPRecommendedListListArrayOutput {
	return i.ToGetTrafficForwardingVIPRecommendedListListArrayOutputWithContext(context.Background())
}

func (i GetTrafficForwardingVIPRecommendedListListArray) ToGetTrafficForwardingVIPRecommendedListListArrayOutputWithContext(ctx context.Context) GetTrafficForwardingVIPRecommendedListListArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetTrafficForwardingVIPRecommendedListListArrayOutput)
}

type GetTrafficForwardingVIPRecommendedListListOutput struct{ *pulumi.OutputState }

func (GetTrafficForwardingVIPRecommendedListListOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetTrafficForwardingVIPRecommendedListList)(nil)).Elem()
}

func (o GetTrafficForwardingVIPRecommendedListListOutput) ToGetTrafficForwardingVIPRecommendedListListOutput() GetTrafficForwardingVIPRecommendedListListOutput {
	return o
}

func (o GetTrafficForwardingVIPRecommendedListListOutput) ToGetTrafficForwardingVIPRecommendedListListOutputWithContext(ctx context.Context) GetTrafficForwardingVIPRecommendedListListOutput {
	return o
}

// (String) Data center information
func (o GetTrafficForwardingVIPRecommendedListListOutput) Datacenter() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetTrafficForwardingVIPRecommendedListList) *string { return v.Datacenter }).(pulumi.StringPtrOutput)
}

// Unique identifer of the GRE virtual IP address (VIP)
func (o GetTrafficForwardingVIPRecommendedListListOutput) Id() pulumi.IntPtrOutput {
	return o.ApplyT(func(v GetTrafficForwardingVIPRecommendedListList) *int { return v.Id }).(pulumi.IntPtrOutput)
}

// (Boolean) Set to true if the virtual IP address (VIP) is a ZIA Private Service Edge
func (o GetTrafficForwardingVIPRecommendedListListOutput) PrivateServiceEdge() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v GetTrafficForwardingVIPRecommendedListList) *bool { return v.PrivateServiceEdge }).(pulumi.BoolPtrOutput)
}

// (String) GRE cluster virtual IP address (VIP)
func (o GetTrafficForwardingVIPRecommendedListListOutput) VirtualIp() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetTrafficForwardingVIPRecommendedListList) *string { return v.VirtualIp }).(pulumi.StringPtrOutput)
}

type GetTrafficForwardingVIPRecommendedListListArrayOutput struct{ *pulumi.OutputState }

func (GetTrafficForwardingVIPRecommendedListListArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetTrafficForwardingVIPRecommendedListList)(nil)).Elem()
}

func (o GetTrafficForwardingVIPRecommendedListListArrayOutput) ToGetTrafficForwardingVIPRecommendedListListArrayOutput() GetTrafficForwardingVIPRecommendedListListArrayOutput {
	return o
}

func (o GetTrafficForwardingVIPRecommendedListListArrayOutput) ToGetTrafficForwardingVIPRecommendedListListArrayOutputWithContext(ctx context.Context) GetTrafficForwardingVIPRecommendedListListArrayOutput {
	return o
}

func (o GetTrafficForwardingVIPRecommendedListListArrayOutput) Index(i pulumi.IntInput) GetTrafficForwardingVIPRecommendedListListOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetTrafficForwardingVIPRecommendedListList {
		return vs[0].([]GetTrafficForwardingVIPRecommendedListList)[vs[1].(int)]
	}).(GetTrafficForwardingVIPRecommendedListListOutput)
}

type GetTrafficForwardingVPNCredentialsLocation struct {
	// (Map of String)
	Extensions map[string]string `pulumi:"extensions"`
	// Unique identifer of the GRE virtual IP address (VIP)
	Id int `pulumi:"id"`
	// (String) The configured name of the entity
	Name string `pulumi:"name"`
}

// GetTrafficForwardingVPNCredentialsLocationInput is an input type that accepts GetTrafficForwardingVPNCredentialsLocationArgs and GetTrafficForwardingVPNCredentialsLocationOutput values.
// You can construct a concrete instance of `GetTrafficForwardingVPNCredentialsLocationInput` via:
//
//	GetTrafficForwardingVPNCredentialsLocationArgs{...}
type GetTrafficForwardingVPNCredentialsLocationInput interface {
	pulumi.Input

	ToGetTrafficForwardingVPNCredentialsLocationOutput() GetTrafficForwardingVPNCredentialsLocationOutput
	ToGetTrafficForwardingVPNCredentialsLocationOutputWithContext(context.Context) GetTrafficForwardingVPNCredentialsLocationOutput
}

type GetTrafficForwardingVPNCredentialsLocationArgs struct {
	// (Map of String)
	Extensions pulumi.StringMapInput `pulumi:"extensions"`
	// Unique identifer of the GRE virtual IP address (VIP)
	Id pulumi.IntInput `pulumi:"id"`
	// (String) The configured name of the entity
	Name pulumi.StringInput `pulumi:"name"`
}

func (GetTrafficForwardingVPNCredentialsLocationArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetTrafficForwardingVPNCredentialsLocation)(nil)).Elem()
}

func (i GetTrafficForwardingVPNCredentialsLocationArgs) ToGetTrafficForwardingVPNCredentialsLocationOutput() GetTrafficForwardingVPNCredentialsLocationOutput {
	return i.ToGetTrafficForwardingVPNCredentialsLocationOutputWithContext(context.Background())
}

func (i GetTrafficForwardingVPNCredentialsLocationArgs) ToGetTrafficForwardingVPNCredentialsLocationOutputWithContext(ctx context.Context) GetTrafficForwardingVPNCredentialsLocationOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetTrafficForwardingVPNCredentialsLocationOutput)
}

// GetTrafficForwardingVPNCredentialsLocationArrayInput is an input type that accepts GetTrafficForwardingVPNCredentialsLocationArray and GetTrafficForwardingVPNCredentialsLocationArrayOutput values.
// You can construct a concrete instance of `GetTrafficForwardingVPNCredentialsLocationArrayInput` via:
//
//	GetTrafficForwardingVPNCredentialsLocationArray{ GetTrafficForwardingVPNCredentialsLocationArgs{...} }
type GetTrafficForwardingVPNCredentialsLocationArrayInput interface {
	pulumi.Input

	ToGetTrafficForwardingVPNCredentialsLocationArrayOutput() GetTrafficForwardingVPNCredentialsLocationArrayOutput
	ToGetTrafficForwardingVPNCredentialsLocationArrayOutputWithContext(context.Context) GetTrafficForwardingVPNCredentialsLocationArrayOutput
}

type GetTrafficForwardingVPNCredentialsLocationArray []GetTrafficForwardingVPNCredentialsLocationInput

func (GetTrafficForwardingVPNCredentialsLocationArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetTrafficForwardingVPNCredentialsLocation)(nil)).Elem()
}

func (i GetTrafficForwardingVPNCredentialsLocationArray) ToGetTrafficForwardingVPNCredentialsLocationArrayOutput() GetTrafficForwardingVPNCredentialsLocationArrayOutput {
	return i.ToGetTrafficForwardingVPNCredentialsLocationArrayOutputWithContext(context.Background())
}

func (i GetTrafficForwardingVPNCredentialsLocationArray) ToGetTrafficForwardingVPNCredentialsLocationArrayOutputWithContext(ctx context.Context) GetTrafficForwardingVPNCredentialsLocationArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetTrafficForwardingVPNCredentialsLocationArrayOutput)
}

type GetTrafficForwardingVPNCredentialsLocationOutput struct{ *pulumi.OutputState }

func (GetTrafficForwardingVPNCredentialsLocationOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetTrafficForwardingVPNCredentialsLocation)(nil)).Elem()
}

func (o GetTrafficForwardingVPNCredentialsLocationOutput) ToGetTrafficForwardingVPNCredentialsLocationOutput() GetTrafficForwardingVPNCredentialsLocationOutput {
	return o
}

func (o GetTrafficForwardingVPNCredentialsLocationOutput) ToGetTrafficForwardingVPNCredentialsLocationOutputWithContext(ctx context.Context) GetTrafficForwardingVPNCredentialsLocationOutput {
	return o
}

// (Map of String)
func (o GetTrafficForwardingVPNCredentialsLocationOutput) Extensions() pulumi.StringMapOutput {
	return o.ApplyT(func(v GetTrafficForwardingVPNCredentialsLocation) map[string]string { return v.Extensions }).(pulumi.StringMapOutput)
}

// Unique identifer of the GRE virtual IP address (VIP)
func (o GetTrafficForwardingVPNCredentialsLocationOutput) Id() pulumi.IntOutput {
	return o.ApplyT(func(v GetTrafficForwardingVPNCredentialsLocation) int { return v.Id }).(pulumi.IntOutput)
}

// (String) The configured name of the entity
func (o GetTrafficForwardingVPNCredentialsLocationOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetTrafficForwardingVPNCredentialsLocation) string { return v.Name }).(pulumi.StringOutput)
}

type GetTrafficForwardingVPNCredentialsLocationArrayOutput struct{ *pulumi.OutputState }

func (GetTrafficForwardingVPNCredentialsLocationArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetTrafficForwardingVPNCredentialsLocation)(nil)).Elem()
}

func (o GetTrafficForwardingVPNCredentialsLocationArrayOutput) ToGetTrafficForwardingVPNCredentialsLocationArrayOutput() GetTrafficForwardingVPNCredentialsLocationArrayOutput {
	return o
}

func (o GetTrafficForwardingVPNCredentialsLocationArrayOutput) ToGetTrafficForwardingVPNCredentialsLocationArrayOutputWithContext(ctx context.Context) GetTrafficForwardingVPNCredentialsLocationArrayOutput {
	return o
}

func (o GetTrafficForwardingVPNCredentialsLocationArrayOutput) Index(i pulumi.IntInput) GetTrafficForwardingVPNCredentialsLocationOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetTrafficForwardingVPNCredentialsLocation {
		return vs[0].([]GetTrafficForwardingVPNCredentialsLocation)[vs[1].(int)]
	}).(GetTrafficForwardingVPNCredentialsLocationOutput)
}

type GetTrafficForwardingVPNCredentialsManagedBy struct {
	// (Map of String)
	Extensions map[string]string `pulumi:"extensions"`
	// Unique identifer of the GRE virtual IP address (VIP)
	Id int `pulumi:"id"`
	// (String) The configured name of the entity
	Name string `pulumi:"name"`
}

// GetTrafficForwardingVPNCredentialsManagedByInput is an input type that accepts GetTrafficForwardingVPNCredentialsManagedByArgs and GetTrafficForwardingVPNCredentialsManagedByOutput values.
// You can construct a concrete instance of `GetTrafficForwardingVPNCredentialsManagedByInput` via:
//
//	GetTrafficForwardingVPNCredentialsManagedByArgs{...}
type GetTrafficForwardingVPNCredentialsManagedByInput interface {
	pulumi.Input

	ToGetTrafficForwardingVPNCredentialsManagedByOutput() GetTrafficForwardingVPNCredentialsManagedByOutput
	ToGetTrafficForwardingVPNCredentialsManagedByOutputWithContext(context.Context) GetTrafficForwardingVPNCredentialsManagedByOutput
}

type GetTrafficForwardingVPNCredentialsManagedByArgs struct {
	// (Map of String)
	Extensions pulumi.StringMapInput `pulumi:"extensions"`
	// Unique identifer of the GRE virtual IP address (VIP)
	Id pulumi.IntInput `pulumi:"id"`
	// (String) The configured name of the entity
	Name pulumi.StringInput `pulumi:"name"`
}

func (GetTrafficForwardingVPNCredentialsManagedByArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetTrafficForwardingVPNCredentialsManagedBy)(nil)).Elem()
}

func (i GetTrafficForwardingVPNCredentialsManagedByArgs) ToGetTrafficForwardingVPNCredentialsManagedByOutput() GetTrafficForwardingVPNCredentialsManagedByOutput {
	return i.ToGetTrafficForwardingVPNCredentialsManagedByOutputWithContext(context.Background())
}

func (i GetTrafficForwardingVPNCredentialsManagedByArgs) ToGetTrafficForwardingVPNCredentialsManagedByOutputWithContext(ctx context.Context) GetTrafficForwardingVPNCredentialsManagedByOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetTrafficForwardingVPNCredentialsManagedByOutput)
}

// GetTrafficForwardingVPNCredentialsManagedByArrayInput is an input type that accepts GetTrafficForwardingVPNCredentialsManagedByArray and GetTrafficForwardingVPNCredentialsManagedByArrayOutput values.
// You can construct a concrete instance of `GetTrafficForwardingVPNCredentialsManagedByArrayInput` via:
//
//	GetTrafficForwardingVPNCredentialsManagedByArray{ GetTrafficForwardingVPNCredentialsManagedByArgs{...} }
type GetTrafficForwardingVPNCredentialsManagedByArrayInput interface {
	pulumi.Input

	ToGetTrafficForwardingVPNCredentialsManagedByArrayOutput() GetTrafficForwardingVPNCredentialsManagedByArrayOutput
	ToGetTrafficForwardingVPNCredentialsManagedByArrayOutputWithContext(context.Context) GetTrafficForwardingVPNCredentialsManagedByArrayOutput
}

type GetTrafficForwardingVPNCredentialsManagedByArray []GetTrafficForwardingVPNCredentialsManagedByInput

func (GetTrafficForwardingVPNCredentialsManagedByArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetTrafficForwardingVPNCredentialsManagedBy)(nil)).Elem()
}

func (i GetTrafficForwardingVPNCredentialsManagedByArray) ToGetTrafficForwardingVPNCredentialsManagedByArrayOutput() GetTrafficForwardingVPNCredentialsManagedByArrayOutput {
	return i.ToGetTrafficForwardingVPNCredentialsManagedByArrayOutputWithContext(context.Background())
}

func (i GetTrafficForwardingVPNCredentialsManagedByArray) ToGetTrafficForwardingVPNCredentialsManagedByArrayOutputWithContext(ctx context.Context) GetTrafficForwardingVPNCredentialsManagedByArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GetTrafficForwardingVPNCredentialsManagedByArrayOutput)
}

type GetTrafficForwardingVPNCredentialsManagedByOutput struct{ *pulumi.OutputState }

func (GetTrafficForwardingVPNCredentialsManagedByOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetTrafficForwardingVPNCredentialsManagedBy)(nil)).Elem()
}

func (o GetTrafficForwardingVPNCredentialsManagedByOutput) ToGetTrafficForwardingVPNCredentialsManagedByOutput() GetTrafficForwardingVPNCredentialsManagedByOutput {
	return o
}

func (o GetTrafficForwardingVPNCredentialsManagedByOutput) ToGetTrafficForwardingVPNCredentialsManagedByOutputWithContext(ctx context.Context) GetTrafficForwardingVPNCredentialsManagedByOutput {
	return o
}

// (Map of String)
func (o GetTrafficForwardingVPNCredentialsManagedByOutput) Extensions() pulumi.StringMapOutput {
	return o.ApplyT(func(v GetTrafficForwardingVPNCredentialsManagedBy) map[string]string { return v.Extensions }).(pulumi.StringMapOutput)
}

// Unique identifer of the GRE virtual IP address (VIP)
func (o GetTrafficForwardingVPNCredentialsManagedByOutput) Id() pulumi.IntOutput {
	return o.ApplyT(func(v GetTrafficForwardingVPNCredentialsManagedBy) int { return v.Id }).(pulumi.IntOutput)
}

// (String) The configured name of the entity
func (o GetTrafficForwardingVPNCredentialsManagedByOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetTrafficForwardingVPNCredentialsManagedBy) string { return v.Name }).(pulumi.StringOutput)
}

type GetTrafficForwardingVPNCredentialsManagedByArrayOutput struct{ *pulumi.OutputState }

func (GetTrafficForwardingVPNCredentialsManagedByArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]GetTrafficForwardingVPNCredentialsManagedBy)(nil)).Elem()
}

func (o GetTrafficForwardingVPNCredentialsManagedByArrayOutput) ToGetTrafficForwardingVPNCredentialsManagedByArrayOutput() GetTrafficForwardingVPNCredentialsManagedByArrayOutput {
	return o
}

func (o GetTrafficForwardingVPNCredentialsManagedByArrayOutput) ToGetTrafficForwardingVPNCredentialsManagedByArrayOutputWithContext(ctx context.Context) GetTrafficForwardingVPNCredentialsManagedByArrayOutput {
	return o
}

func (o GetTrafficForwardingVPNCredentialsManagedByArrayOutput) Index(i pulumi.IntInput) GetTrafficForwardingVPNCredentialsManagedByOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) GetTrafficForwardingVPNCredentialsManagedBy {
		return vs[0].([]GetTrafficForwardingVPNCredentialsManagedBy)[vs[1].(int)]
	}).(GetTrafficForwardingVPNCredentialsManagedByOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*TrafficForwardingGRETunnelLastModifiedByInput)(nil)).Elem(), TrafficForwardingGRETunnelLastModifiedByArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*TrafficForwardingGRETunnelLastModifiedByArrayInput)(nil)).Elem(), TrafficForwardingGRETunnelLastModifiedByArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*TrafficForwardingGRETunnelPrimaryDestVipInput)(nil)).Elem(), TrafficForwardingGRETunnelPrimaryDestVipArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*TrafficForwardingGRETunnelPrimaryDestVipArrayInput)(nil)).Elem(), TrafficForwardingGRETunnelPrimaryDestVipArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*TrafficForwardingGRETunnelSecondaryDestVipInput)(nil)).Elem(), TrafficForwardingGRETunnelSecondaryDestVipArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*TrafficForwardingGRETunnelSecondaryDestVipArrayInput)(nil)).Elem(), TrafficForwardingGRETunnelSecondaryDestVipArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*TrafficForwardingStaticIPLastModifiedByInput)(nil)).Elem(), TrafficForwardingStaticIPLastModifiedByArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*TrafficForwardingStaticIPLastModifiedByArrayInput)(nil)).Elem(), TrafficForwardingStaticIPLastModifiedByArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*TrafficForwardingStaticIPManagedByInput)(nil)).Elem(), TrafficForwardingStaticIPManagedByArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*TrafficForwardingStaticIPManagedByArrayInput)(nil)).Elem(), TrafficForwardingStaticIPManagedByArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetTrafficForwardingGREInternalIPRangeListInput)(nil)).Elem(), GetTrafficForwardingGREInternalIPRangeListArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetTrafficForwardingGREInternalIPRangeListArrayInput)(nil)).Elem(), GetTrafficForwardingGREInternalIPRangeListArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetTrafficForwardingGRETunnelLastModifiedByInput)(nil)).Elem(), GetTrafficForwardingGRETunnelLastModifiedByArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetTrafficForwardingGRETunnelLastModifiedByArrayInput)(nil)).Elem(), GetTrafficForwardingGRETunnelLastModifiedByArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetTrafficForwardingGRETunnelManagedByInput)(nil)).Elem(), GetTrafficForwardingGRETunnelManagedByArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetTrafficForwardingGRETunnelManagedByArrayInput)(nil)).Elem(), GetTrafficForwardingGRETunnelManagedByArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetTrafficForwardingGRETunnelPrimaryDestVipInput)(nil)).Elem(), GetTrafficForwardingGRETunnelPrimaryDestVipArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetTrafficForwardingGRETunnelPrimaryDestVipArrayInput)(nil)).Elem(), GetTrafficForwardingGRETunnelPrimaryDestVipArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetTrafficForwardingGRETunnelSecondaryDestVipInput)(nil)).Elem(), GetTrafficForwardingGRETunnelSecondaryDestVipArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetTrafficForwardingGRETunnelSecondaryDestVipArrayInput)(nil)).Elem(), GetTrafficForwardingGRETunnelSecondaryDestVipArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetTrafficForwardingStaticIPLastModifiedByInput)(nil)).Elem(), GetTrafficForwardingStaticIPLastModifiedByArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetTrafficForwardingStaticIPLastModifiedByArrayInput)(nil)).Elem(), GetTrafficForwardingStaticIPLastModifiedByArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetTrafficForwardingStaticIPManagedByInput)(nil)).Elem(), GetTrafficForwardingStaticIPManagedByArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetTrafficForwardingStaticIPManagedByArrayInput)(nil)).Elem(), GetTrafficForwardingStaticIPManagedByArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetTrafficForwardingVIPRecommendedListListInput)(nil)).Elem(), GetTrafficForwardingVIPRecommendedListListArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetTrafficForwardingVIPRecommendedListListArrayInput)(nil)).Elem(), GetTrafficForwardingVIPRecommendedListListArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetTrafficForwardingVPNCredentialsLocationInput)(nil)).Elem(), GetTrafficForwardingVPNCredentialsLocationArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetTrafficForwardingVPNCredentialsLocationArrayInput)(nil)).Elem(), GetTrafficForwardingVPNCredentialsLocationArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetTrafficForwardingVPNCredentialsManagedByInput)(nil)).Elem(), GetTrafficForwardingVPNCredentialsManagedByArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*GetTrafficForwardingVPNCredentialsManagedByArrayInput)(nil)).Elem(), GetTrafficForwardingVPNCredentialsManagedByArray{})
	pulumi.RegisterOutputType(TrafficForwardingGRETunnelLastModifiedByOutput{})
	pulumi.RegisterOutputType(TrafficForwardingGRETunnelLastModifiedByArrayOutput{})
	pulumi.RegisterOutputType(TrafficForwardingGRETunnelPrimaryDestVipOutput{})
	pulumi.RegisterOutputType(TrafficForwardingGRETunnelPrimaryDestVipArrayOutput{})
	pulumi.RegisterOutputType(TrafficForwardingGRETunnelSecondaryDestVipOutput{})
	pulumi.RegisterOutputType(TrafficForwardingGRETunnelSecondaryDestVipArrayOutput{})
	pulumi.RegisterOutputType(TrafficForwardingStaticIPLastModifiedByOutput{})
	pulumi.RegisterOutputType(TrafficForwardingStaticIPLastModifiedByArrayOutput{})
	pulumi.RegisterOutputType(TrafficForwardingStaticIPManagedByOutput{})
	pulumi.RegisterOutputType(TrafficForwardingStaticIPManagedByArrayOutput{})
	pulumi.RegisterOutputType(GetTrafficForwardingGREInternalIPRangeListOutput{})
	pulumi.RegisterOutputType(GetTrafficForwardingGREInternalIPRangeListArrayOutput{})
	pulumi.RegisterOutputType(GetTrafficForwardingGRETunnelLastModifiedByOutput{})
	pulumi.RegisterOutputType(GetTrafficForwardingGRETunnelLastModifiedByArrayOutput{})
	pulumi.RegisterOutputType(GetTrafficForwardingGRETunnelManagedByOutput{})
	pulumi.RegisterOutputType(GetTrafficForwardingGRETunnelManagedByArrayOutput{})
	pulumi.RegisterOutputType(GetTrafficForwardingGRETunnelPrimaryDestVipOutput{})
	pulumi.RegisterOutputType(GetTrafficForwardingGRETunnelPrimaryDestVipArrayOutput{})
	pulumi.RegisterOutputType(GetTrafficForwardingGRETunnelSecondaryDestVipOutput{})
	pulumi.RegisterOutputType(GetTrafficForwardingGRETunnelSecondaryDestVipArrayOutput{})
	pulumi.RegisterOutputType(GetTrafficForwardingStaticIPLastModifiedByOutput{})
	pulumi.RegisterOutputType(GetTrafficForwardingStaticIPLastModifiedByArrayOutput{})
	pulumi.RegisterOutputType(GetTrafficForwardingStaticIPManagedByOutput{})
	pulumi.RegisterOutputType(GetTrafficForwardingStaticIPManagedByArrayOutput{})
	pulumi.RegisterOutputType(GetTrafficForwardingVIPRecommendedListListOutput{})
	pulumi.RegisterOutputType(GetTrafficForwardingVIPRecommendedListListArrayOutput{})
	pulumi.RegisterOutputType(GetTrafficForwardingVPNCredentialsLocationOutput{})
	pulumi.RegisterOutputType(GetTrafficForwardingVPNCredentialsLocationArrayOutput{})
	pulumi.RegisterOutputType(GetTrafficForwardingVPNCredentialsManagedByOutput{})
	pulumi.RegisterOutputType(GetTrafficForwardingVPNCredentialsManagedByArrayOutput{})
}
