// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace zscaler.PulumiPackage.Zia
{
    public static class GetZIATrafficForwardingVIPRecommendedList
    {
        /// <summary>
        /// Use the **zia_gre_vip_recommended_list** data source to get information about a list of recommended GRE tunnel virtual IP addresses (VIPs), based on source IP address or latitude/longitude coordinates.
        /// </summary>
        public static Task<GetZIATrafficForwardingVIPRecommendedListResult> InvokeAsync(GetZIATrafficForwardingVIPRecommendedListArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetZIATrafficForwardingVIPRecommendedListResult>("zia:index/getZIATrafficForwardingVIPRecommendedList:getZIATrafficForwardingVIPRecommendedList", args ?? new GetZIATrafficForwardingVIPRecommendedListArgs(), options.WithDefaults());

        /// <summary>
        /// Use the **zia_gre_vip_recommended_list** data source to get information about a list of recommended GRE tunnel virtual IP addresses (VIPs), based on source IP address or latitude/longitude coordinates.
        /// </summary>
        public static Output<GetZIATrafficForwardingVIPRecommendedListResult> Invoke(GetZIATrafficForwardingVIPRecommendedListInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetZIATrafficForwardingVIPRecommendedListResult>("zia:index/getZIATrafficForwardingVIPRecommendedList:getZIATrafficForwardingVIPRecommendedList", args ?? new GetZIATrafficForwardingVIPRecommendedListInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetZIATrafficForwardingVIPRecommendedListArgs : global::Pulumi.InvokeArgs
    {
        [Input("geoOverride")]
        public bool? GeoOverride { get; set; }

        [Input("requiredCount")]
        public int? RequiredCount { get; set; }

        [Input("routableIp")]
        public bool? RoutableIp { get; set; }

        /// <summary>
        /// (String) The public source IP address.
        /// </summary>
        [Input("sourceIp")]
        public string? SourceIp { get; set; }

        public GetZIATrafficForwardingVIPRecommendedListArgs()
        {
        }
        public static new GetZIATrafficForwardingVIPRecommendedListArgs Empty => new GetZIATrafficForwardingVIPRecommendedListArgs();
    }

    public sealed class GetZIATrafficForwardingVIPRecommendedListInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("geoOverride")]
        public Input<bool>? GeoOverride { get; set; }

        [Input("requiredCount")]
        public Input<int>? RequiredCount { get; set; }

        [Input("routableIp")]
        public Input<bool>? RoutableIp { get; set; }

        /// <summary>
        /// (String) The public source IP address.
        /// </summary>
        [Input("sourceIp")]
        public Input<string>? SourceIp { get; set; }

        public GetZIATrafficForwardingVIPRecommendedListInvokeArgs()
        {
        }
        public static new GetZIATrafficForwardingVIPRecommendedListInvokeArgs Empty => new GetZIATrafficForwardingVIPRecommendedListInvokeArgs();
    }


    [OutputType]
    public sealed class GetZIATrafficForwardingVIPRecommendedListResult
    {
        public readonly bool? GeoOverride;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly ImmutableArray<Outputs.GetZIATrafficForwardingVIPRecommendedListListResult> Lists;
        public readonly int? RequiredCount;
        public readonly bool? RoutableIp;
        /// <summary>
        /// (String) The public source IP address.
        /// </summary>
        public readonly string? SourceIp;

        [OutputConstructor]
        private GetZIATrafficForwardingVIPRecommendedListResult(
            bool? geoOverride,

            string id,

            ImmutableArray<Outputs.GetZIATrafficForwardingVIPRecommendedListListResult> lists,

            int? requiredCount,

            bool? routableIp,

            string? sourceIp)
        {
            GeoOverride = geoOverride;
            Id = id;
            Lists = lists;
            RequiredCount = requiredCount;
            RoutableIp = routableIp;
            SourceIp = sourceIp;
        }
    }
}
