env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  NUGET_PUBLISH_KEY: ${{ secrets.NUGET_PUBLISH_KEY }}
  PROVIDER: zia
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
  PULUMI_API: https://api.pulumi.com
  PULUMI_GO_DEP_ROOT: ${{ github.workspace }}/..
  PULUMI_LOCAL_NUGET: ${{ github.workspace }}/nuget
  PULUMI_TEST_OWNER: "zscaler"
  PYPI_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
  PYPI_USERNAME: "__token__"
  ZIA_USERNAME: ${{ secrets.ZIA_USERNAME }}
  ZIA_PASSWORD: ${{ secrets.ZIA_PASSWORD }}
  ZIA_API_KEY: ${{ secrets.ZIA_API_KEY }}
  ZIA_CLOUD: ${{ secrets.ZIA_CLOUD }}
  TRAVIS_OS_NAME: linux

jobs:
  command-dispatch-for-testing:
    name: command-dispatch-for-testing
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - uses: peter-evans/slash-command-dispatch@v3
      with:
        commands: run-acceptance-tests
        issue-type: pull-request
        permission: write
        reaction-token: ${{ secrets.GITHUB_TOKEN }}
        repository: zscaler/pulumi-zia
        token: ${{ secrets.PULUMI_BOT_TOKEN }}
    strategy: {}
"on":
  issue_comment:
    types:
    - created
    - edited
