// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Use the **zia_firewall_filtering_time_window** data source to get information about a time window option available in the Zscaler Internet Access cloud firewall. This data source can then be associated with a ZIA firewall filtering rule.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as zia from "@pulumi/zia";
 *
 * const workHours = zia.getZIATimeWindow({
 *     name: "Work hours",
 * });
 * ```
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as zia from "@pulumi/zia";
 *
 * const weekends = zia.getZIATimeWindow({
 *     name: "Weekends",
 * });
 * ```
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as zia from "@pulumi/zia";
 *
 * const offHours = zia.getZIATimeWindow({
 *     name: "Off hours",
 * });
 * ```
 */
export function getZIATimeWindow(args?: GetZIATimeWindowArgs, opts?: pulumi.InvokeOptions): Promise<GetZIATimeWindowResult> {
    args = args || {};

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("zia:index/getZIATimeWindow:getZIATimeWindow", {
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getZIATimeWindow.
 */
export interface GetZIATimeWindowArgs {
    /**
     * The name of the time window to be exported.
     */
    name?: string;
}

/**
 * A collection of values returned by getZIATimeWindow.
 */
export interface GetZIATimeWindowResult {
    /**
     * (String). The supported values are:
     */
    readonly dayOfWeeks: string[];
    /**
     * (String)
     */
    readonly endTime: number;
    readonly id: number;
    readonly name?: string;
    /**
     * (String)
     */
    readonly startTime: number;
}
/**
 * Use the **zia_firewall_filtering_time_window** data source to get information about a time window option available in the Zscaler Internet Access cloud firewall. This data source can then be associated with a ZIA firewall filtering rule.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as zia from "@pulumi/zia";
 *
 * const workHours = zia.getZIATimeWindow({
 *     name: "Work hours",
 * });
 * ```
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as zia from "@pulumi/zia";
 *
 * const weekends = zia.getZIATimeWindow({
 *     name: "Weekends",
 * });
 * ```
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as zia from "@pulumi/zia";
 *
 * const offHours = zia.getZIATimeWindow({
 *     name: "Off hours",
 * });
 * ```
 */
export function getZIATimeWindowOutput(args?: GetZIATimeWindowOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetZIATimeWindowResult> {
    return pulumi.output(args).apply((a: any) => getZIATimeWindow(a, opts))
}

/**
 * A collection of arguments for invoking getZIATimeWindow.
 */
export interface GetZIATimeWindowOutputArgs {
    /**
     * The name of the time window to be exported.
     */
    name?: pulumi.Input<string>;
}
